
with source as (

    select * from {{ source('raw_greenhouse', 'job_history') }}

),

renamed as (

    select
        job_id,
        updated_at,
        _fivetran_synced,
        closed_at,
        confidential,
        notes,
        requisition_id,
        status,
        _fivetran_deleted,
        created_at,
        custom_budgeted_compensation_2,
        custom_consulting_team,
        custom_desired_entry,
        custom_desired_location,
        custom_employee_contingent_worker_type,
        custom_employment_type,
        custom_engineering_team,
        custom_evergreen_req_,
        custom_fpa_predicted_start,
        custom_has_the_job_description_been_provided_to_recruiting_,
        custom_headcount_type,
        custom_hm_location,
        custom_hm_name,
        custom_hm_title,
        custom_hot_job,
        custom_how_will_adding_this_position_help_us_reach_the_goals_of_this_department_and_ultimately_the_goals_of_the_company_,
        custom_if_net_new_head_to_current_fiscal_year_please_describe_reasoning_to_pull_this_hire_ahead,
        custom_impact_if_position_is_not_filled,
        custom_incubent_name_backfill_only_,
        custom_incumbent_internal_seniority_level_backfill_only_1,
        custom_incumbent_salary_backfill_only_,
        custom_incumbent_separation_date_backfill_only_,
        custom_incumbent_separation_reason_backfill_only_,
        custom_internal_seniority_level,
        custom_internal_seniority_level_hr_band,
        custom_job_profile,
        custom_justification_to_hire,
        custom_management_role,
        custom_notes_further_context_if_necessary_,
        custom_ote_split,
        custom_partners_team,
        custom_primary_location,
        custom_req_id_1,
        custom_salary_1,
        custom_sales_market_segment,
        custom_segment,
        custom_stock_options,
        custom_stock_options_1,
        custom_stock_options_2,
        custom_sup_org_hiring_manager,
        custom_target_locations,
        custom_team,
        custom_territory,
        custom_time_type,
        custom_total_cash_compensation_local_currency_,
        custom_total_compensation_ote_range,
        custom_training_team,
        custom_value_based_equity,
        custom_what_are_the_main_short_and_long_term_responsibilities_of_this_position_,
        id,
        name,
        custom_hm_name_linked_in_profile_,
        custom_base_ote_approval_guidelines,
        custom_equity_approval_guidelines,
        custom_sign_on_approval_guidelines,
        custom_company,
        custom_colorado_minimum_rate,
        custom_colorado_pay_range,
        custom_linked_in_remote_posting,
        custom_pay_type,
        is_template

    from source

)

select * from renamed
