
with source as (

    select * from {{ source('raw_cloud_billing_stripe', 'checkout_session') }}

),

renamed as (

    select
        id,
        _fivetran_synced,
        after_expiration_allow_promotion_codes,
        after_expiration_enabled,
        after_expiration_expires_at,
        after_expiration_url,
        allow_promotion_codes,
        automatic_tax_enabled,
        automatic_tax_status,
        billing_address_collection,
        cancel_url,
        client_reference_id,
        consent_collection_promotions,
        consent_promotions,
        currency,
        customer_id,
        expires_at,
        livemode,
        locale,
        metadata,
        mode,
        object,
        payment_intent_id,
        payment_link,
        payment_method_options_acss_debit_currency,
        payment_method_options_acss_debit_custom_mandate_url,
        payment_method_options_acss_debit_interval_description,
        payment_method_options_acss_debit_payment_schedule,
        payment_method_options_acss_debit_setup_future_usage,
        payment_method_options_acss_debit_transaction_type,
        payment_method_options_acss_debit_verification_method,
        payment_method_options_affirm_setup_future_usage,
        payment_method_options_afterpay_clearpay_setup_future_usage,
        payment_method_options_alipay_setup_future_usage,
        payment_method_options_au_becs_debit_setup_future_usage,
        payment_method_options_bacs_debit_setup_future_usage,
        payment_method_options_bancontact_setup_future_usage,
        payment_method_options_boleto_expires_after_days,
        payment_method_options_boleto_setup_future_usage,
        payment_method_options_card_installments_enabled,
        payment_method_options_card_setup_future_usage,
        payment_method_options_card_statement_descriptor_suffix_kana,
        payment_method_options_card_statement_descriptor_suffix_kanji,
        payment_method_options_customer_balance_country,
        payment_method_options_customer_balance_funding_type,
        payment_method_options_customer_balance_requested_address_types,
        payment_method_options_customer_balance_setup_future_usage,
        payment_method_options_customer_balance_type,
        payment_method_options_eps_setup_future_usage,
        payment_method_options_fpx_setup_future_usage,
        payment_method_options_giropay_setup_future_usage,
        payment_method_options_grabpay_setup_future_usage,
        payment_method_options_ideal_setup_future_usage,
        payment_method_options_klarna_setup_future_usage,
        payment_method_options_konbini_expires_after_days,
        payment_method_options_konbini_setup_future_usage,
        payment_method_options_oxxo_expires_after_days,
        payment_method_options_oxxo_setup_future_usage,
        payment_method_options_p_24_setup_future_usage,
        payment_method_options_paynow_setup_future_usage,
        payment_method_options_sepa_debit_setup_future_usage,
        payment_method_options_sofort_setup_future_usage,
        payment_method_options_us_bank_account_financial_connections,
        payment_method_options_us_bank_account_setup_future_usage,
        payment_method_options_us_bank_account_verification_method,
        payment_status,
        phone_number_collection_enabled,
        recovered_from,
        setup_intent_id,
        shipping_city,
        shipping_country,
        shipping_line_1,
        shipping_line_2,
        shipping_name,
        shipping_postal_code,
        shipping_rate_amount_subtotal,
        shipping_rate_amount_tax,
        shipping_rate_amount_total,
        shipping_rate_shipping_rate_id,
        shipping_state,
        status,
        submit_type,
        subscription_id,
        success_url,
        tax_id_collection_enabled,
        total_details_amount_discount,
        total_details_amount_shipping,
        total_details_amount_tax,
        url

    from source

)

select * from renamed
