# Big Query Specific Configs
# https://docs.getdbt.com/reference/resource-configs/bigquery-configs
name: "elastic_dbt_sources"
version: "1.0.0"
config-version: 2
profile: "dbt"

# =====
# Paths
# =====
macro-paths: ["macros"]
model-paths: ["models"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages", "logs"]
