
with source as (

    select * from {{ source('raw_contentstack', 'blog') }}

),

renamed as (

    select
        uid,
        created_at,
        created_by,
        updated_at,
        updated_by,
        title,
        url,
        title_l10n,
        author,
        publish_date,
        category,
        weekly_category,
        product,
        level,
        industry,
        popular_topics,
        services_events,
        use_case,
        versions,
        thumbnail_image_uid,
        thumbnail_image_created_at,
        thumbnail_image_updated_at,
        thumbnail_image_created_by,
        thumbnail_image_updated_by,
        thumbnail_image_content_type,
        thumbnail_image_file_size,
        thumbnail_image_tags,
        thumbnail_image_filename,
        thumbnail_image_url,
        thumbnail_image_acl_roles,
        thumbnail_image_acl_others_read,
        thumbnail_image_acl_others_create,
        thumbnail_image_acl_others_update,
        thumbnail_image_acl_others_delete,
        thumbnail_image_acl_others_sub_acl_read,
        thumbnail_image_acl_others_sub_acl_create,
        thumbnail_image_acl_others_sub_acl_update,
        thumbnail_image_acl_others_sub_acl_delete,
        thumbnail_image_acl_others_sub_acl_publish,
        thumbnail_image_is_dir,
        thumbnail_image_version,
        thumbnail_image_title,
        thumbnail_image_description,
        thumbnail_image_publish_details_environment,
        thumbnail_image_publish_details_locale,
        thumbnail_image_publish_details_time,
        thumbnail_image_publish_details_user,
        thumbnail_image_parent_uuid,
        full_bleed_image_uid,
        full_bleed_image_created_at,
        full_bleed_image_updated_at,
        full_bleed_image_created_by,
        full_bleed_image_updated_by,
        full_bleed_image_content_type,
        full_bleed_image_file_size,
        full_bleed_image_tags,
        full_bleed_image_filename,
        full_bleed_image_url,
        full_bleed_image_description,
        full_bleed_image_acl_roles,
        full_bleed_image_acl_others_read,
        full_bleed_image_acl_others_create,
        full_bleed_image_acl_others_update,
        full_bleed_image_acl_others_delete,
        full_bleed_image_acl_others_sub_acl_read,
        full_bleed_image_acl_others_sub_acl_create,
        full_bleed_image_acl_others_sub_acl_update,
        full_bleed_image_acl_others_sub_acl_delete,
        full_bleed_image_acl_others_sub_acl_publish,
        full_bleed_image_is_dir,
        full_bleed_image_version,
        full_bleed_image_title,
        full_bleed_image_publish_details_environment,
        full_bleed_image_publish_details_locale,
        full_bleed_image_publish_details_time,
        full_bleed_image_publish_details_user,
        full_bleed_image_parent_uid,
        abstract_l10n,
        disclaimer,
        body_l10n,
        markdown_l10n,
        seo_seo_title_l10n,
        seo_seo_description_l10n,
        seo_canonical_tag,
        seo_twitter_creator,
        seo_og_markup_facebook_profile_id,
        seo_social_paragraph_l10n,
        locale,
        tags,
        acl_roles,
        acl_others_read,
        acl_others_create,
        acl_others_update,
        acl_others_delete,
        acl_others_sub_acl_read,
        acl_others_sub_acl_create,
        acl_others_sub_acl_update,
        acl_others_sub_acl_delete,
        acl_others_sub_acl_publish,
        _version,
        publish_details_environment,
        publish_details_locale,
        publish_details_time,
        publish_details_user,
        newsfeed,
        rtp_general_l10n,
        rtp_homepage_l10n

    from source

)

select * from renamed
