
with source as (

    select * from {{ source('raw_netsuite_sa', 'change_request_history') }}

),

renamed as (

    select
        change_request_id,
        _fivetran_deleted,
        _fivetran_synced,
        additional_approvers_sort_ord,
        affected_bundle_id,
        all_approvers_reason,
        approval_override_by_id,
        approval_status_id,
        approver_notes,
        archiving_status_id,
        auditor_assigned,
        autoapprove_based_on_bundle,
        budgeted_cost,
        budgeted_hours,
        change_level_required_id,
        change_overview,
        change_request_extid,
        change_request_name,
        change_type_id,
        completion_status_id,
        created_from_id,
        date_created,
        date_deleted,
        deployment_date,
        external_audit_comments,
        external_audit_status_id,
        external_change_request_numbe,
        external_link,
        flo_incident_number,
        impact_analysis,
        import_from_processes,
        include_impacted_customziatio,
        internal_audit_comments,
        internal_audit_status_id,
        is_inactive,
        jira_approve_from_ui,
        last_external_audit_id,
        last_internal_audit_id,
        last_modified_date,
        lastapprover,
        manually_change,
        new_customization_to_add,
        order_approver,
        originated_system,
        originating_case_company_id,
        originating_case_id,
        parent_change_request_id,
        parent_id,
        parent_prod_cr,
        priority_level_id,
        project_id,
        proposed_customizations,
        reason,
        reason_for_role_or_permission,
        rejected_by_id,
        remove_inactive_customization,
        results_filter,
        results_filter_file,
        sampled_for_audit_id,
        sendalert,
        single_policy_reference_id,
        sod_failed_to_add_rolespermis,
        sod_post_approval_pending,
        source_environment_id,
        stage_id,
        status_bar_state_id,
        target_account,
        target_environment_id,
        do_not_respider_automatically,
        service_now_sys_id,
        sod_post_approval_pending_dep,
        affected_employees_tmp,
        select_current_employees,
        all_current_employees_with_th,
        group_order_approver,
        all_current_and_future_employ,
        sod_exemption_type_id,
        external_user,
        user_provisioning_error,
        access_type_id,
        offboarding_date,
        timezone_id,
        offboarding_date_utc,
        auto_role_removal_done,
        offboarding_time,
        auto_role_added_done,
        affected_bundleapp_id,
        partition_date

    from source

)

select * from renamed
