
with source as (

    select * from {{ source('raw_netsuite_sa', 'payment_file_administration') }}

),

renamed as (

    select
        payment_file_administration_id,
        _fivetran_deleted,
        _fivetran_synced,
        account_id,
        aggregate_by_payee,
        aggregation_method,
        amount_map,
        amount_of_applied_credits,
        applied_credits,
        approval_level_id,
        bank_account_id,
        batch_details_id,
        batch_map_of_entity_amounts,
        batch_number,
        batch_status_id,
        batch_time_stamp,
        batch_with_credit,
        bcc_receivers,
        cc_receivers,
        class_id,
        date_created,
        date_deleted,
        department_id,
        direct_debit_type_id,
        discount_map,
        email_notification_sender_id,
        email_receivers,
        exchange_rates,
        file_creation_date,
        file_generation_suitelet_data,
        file_processed_id,
        file_reference,
        freemarker_trans_hash_string,
        from_batch,
        is_inactive,
        is_licensed,
        is_using_ss_2_0,
        journal_keys,
        last_check_number,
        last_modified_date,
        last_process_inititated_id,
        location_id,
        notification_mails_per_paymen,
        notification_subject,
        parent_deployment,
        parent_id,
        partially_paid_keys,
        payment_aggregation_list,
        payment_creation_queue,
        payment_file_administration_ex,
        payment_file_administration_na,
        payment_file_administration_nu,
        payment_file_creation_timesta,
        payment_mode_id,
        payment_portal_batch_id,
        payment_type_id,
        payments_for_notification,
        payments_for_processing_amoun,
        payments_for_processing_disco,
        payments_for_processing_id,
        payments_for_reversal,
        posting_period_id,
        previous_approval_level_id,
        priority_in_queue_id,
        process_date,
        process_user_id,
        processing_errors,
        reference_note,
        removed_keys,
        reprocess_flag,
        reversal_date,
        reversal_period,
        reversal_reason_per_payment,
        sequence_id,
        subsidiary_id,
        total_amount,
        total_transactions,
        transaction_entities,
        updated_count,
        updated_entity_records,
        is_ibf_vpp,
        is_file_encrypted,
        reversed_transaction_count,
        from_eft_bill_payment_page,
        is_global_payment

    from source

)

select * from renamed
