
with source as (

    select * from {{ source('raw_netsuite', 'tax_items_history') }}

),

renamed as (

    select
        avatax_taxcode,
        billings_account_id,
        billings_discount_account_id,
        capacity_id,
        capital_goods,
        cash_register,
        category_0,
        code_of_supply_id,
        commodity_code,
        date_last_modified,
        deemed_supply,
        deferred_id,
        description,
        do_not_sync_to_salesforce,
        duplicate_invoice,
        einvoice,
        elastic_cloud_item_id,
        elastic_cloud_item_type_id,
        end_of_life_date,
        end_of_ms_date,
        exempt_from_billing_script,
        full_name,
        gcc_member_state,
        government,
        ha_id,
        import_0,
        import_vat,
        income_account_id,
        isinactive,
        item_category_id,
        item_extid,
        item_id,
        maintenancesupport_type_id,
        maximum_quantity_hidden,
        mpn,
        ms_pricing_option_id,
        name,
        nature_of_transaction_codes_id,
        node_count,
        nondeductible,
        nondeductible_expense_accou_id,
        nondeductible_rate_derived__id,
        nonoperational_transaction,
        nontaxable,
        non_recoverable,
        non_resident,
        notional_rate_derived_from_id,
        no_tax_credit,
        no_tax_invoice,
        optout_ms,
        other_tax_evidence,
        outside_customs_territory,
        paid,
        parent_id,
        partial_tax_credit,
        planned_hours,
        product_category_id,
        product_family_id,
        product_family_v2_id,
        product_line_id,
        product_type_id,
        purchaser_issued_invoice,
        quantity_cap_hidden_id,
        quantity_type_id,
        rate,
        reduced_rate,
        region_id,
        related_found_standard_item_id,
        renewals_exclusion,
        renew_with_id,
        replaced_with_id,
        reverse_charge_code,
        rev_rec_end_date,
        rev_rec_start_date,
        special_reduced_rate,
        special_territory,
        ssd_id,
        supplementary_unit_id,
        supplementary_unit__abberviat,
        surcharge,
        suspended,
        tax_city,
        tax_county,
        tax_exemption_reason_id,
        tax_state,
        tax_type_id,
        tax_zipcode,
        term__contract_pricing_type_id,
        training_event_id,
        triplicate_invoice,
        type_of_goods_id,
        udf1,
        udf2,
        unknown_tax_credit,
        un_number,
        vendorname,
        vendor_id,
        custom_sku,
        embedded_quantity,
        n_606lt_dr_account_id,
        n_606_revenue_account_id,
        n_606_st_dr_account_id,
        ssp_category_id,
        ssp_family_id,
        subject_to_allocation,
        volume_discounted_in_quoting

    from source

)

select * from renamed
