
with source as (

    select * from {{ source('raw_netsuite', 'configuration_and_stats_history') }}

),

renamed as (

    select
        autospider_portlet_initiate_d,
        auto_archive_folder,
        auto_spider_enabled,
        auto_spider_frequency_id,
        auto_spider_last_run_date,
        bundles_to_ignore,
        bundle_version,
        configuration_and_stats_extid,
        configuration_and_stats_id,
        current_time_of_day,
        customizations_with_default_s,
        customizations_with_no_active,
        customizations_with_no_descri,
        custom_fields_with_no_help,
        date_created,
        date_installed,
        disable_spider_last_use_repor,
        enable_auto_archive,
        enable_auto_process_issue,
        enable_remote_status_report,
        end_time,
        erd_usage_date,
        fields_with_no_parent,
        files_pending_to_process,
        form_join,
        installed_from,
        is_inactive,
        jira_compare_token,
        jira_key,
        jira_pass,
        jira_user,
        last_completed_spider,
        last_manual_spider_trigger_by,
        last_manual_spider_trigger_da,
        last_modified_date,
        last_updated,
        list_joins,
        main_administrator_id,
        number_of_non_strongpoint_ss_,
        number_of_queues,
        parent_id,
        potentially_unused_scripts,
        process_issue_approver_id,
        process_issue_assigned_id,
        record_types_with_unfinished_,
        remaining_objects_to_join,
        retrometrics_attempt,
        saved_searches_spider_time_li,
        schedule_script_queues_set,
        scripts_with_floend_tags,
        scripts_with_flostart_tags,
        scripts_with_no_audit_tags,
        script_joins,
        search_join,
        segments_sets,
        sessions_lost,
        sourcing_join,
        spider__back_end_date,
        spider__back_end_id,
        spider__back_end_lr,
        spider__front_end_date,
        spider__front_end_date_lr,
        spider__front_end_id,
        spider__gather_utilization_me,
        spider__gather_utilization__id,
        spider__gather_utiliz__metada,
        spider__make_joins_date,
        spider__make_joins_id,
        spider__make_joins_lr,
        spider__script_parser_date,
        spider__script_parser_id,
        spider__script_parser_lr,
        standard_field_impact_analysi,
        start_time,
        stop_scripts,
        strongpoint_spider_2_0_tracke,
        total_change_requests,
        total_customizations,
        total_joins,
        total_policies,
        total_process_issue,
        unused_fields,
        unused_records,
        unused_searches,
        workflow_joins,
        enable_opportunistic_clearanc,
        include_all_standard_fields,
        include_only_script_related_s,
        spider__all_standard_fields_id,
        base_menu_json,
        compliance_menu_json,
        script_management_menu_json,
        show_menu_items,
        case_to_cr_configuration,
        case_to_cr_feature_init,
        enable_case_to_change_request,
        issue_deployment_statuses,
        spider_run_status

    from source

)

select * from renamed
