
with source as (

    select * from {{ source('raw_netsuite', 'item_fulfillments_history') }}

),

renamed as (

    select
        accounting_period_id,
        ancillary_endorsement,
        b13a_filling_option,
        b13a_statement_data,
        backup_ship_notification_email,
        billaddress,
        booking_confirmation_number,
        carrier_identification_code,
        created_by_id,
        currency_id,
        date_blanket_period_end,
        date_blanket_period_start,
        date_closed,
        date_created,
        date_future_shipping,
        date_home_delivery,
        date_last_modified,
        date_license,
        date_sales_effective,
        date_transaction,
        delivery_instructions,
        eccn,
        email,
        entity_id,
        entry_number,
        exchange_rate,
        export_type,
        fax,
        fedex_ship_alert,
        fob,
        handling_cost,
        has_cert_of_origin,
        has_commercial_invoice,
        has_nafta_cert_of_origin,
        has_pro_forma_invoice,
        hold_at_location_address_one,
        hold_at_location_address_three,
        hold_at_location_address_two,
        hold_at_location_city,
        hold_at_location_country,
        hold_at_location_loc_phone,
        hold_at_location_phone,
        hold_at_location_state,
        hold_at_location_zip,
        home_delivery_type,
        international_exemption_number,
        in_bond_code,
        is_certified_mail,
        is_fdx_signature_home_delivery,
        is_held_at_location,
        is_holiday_delivery,
        is_inside_delivery,
        is_inside_pickup,
        is_intercompany,
        is_memorized,
        is_online_bill_pay,
        is_related_parties_transaction,
        is_routed_export_transaction,
        is_saturday_delivery,
        is_saturday_pickup,
        is_saturday_service,
        is_tax_reg_override,
        is_visible_in_customer_center,
        is_weekend_delivery,
        license_exception,
        license_number,
        memo,
        message,
        method_of_transport,
        needs_bill,
        notification_email_message,
        promotion_code_id,
        reason_for_export,
        recipient_customs_id,
        recipient_customs_id_type,
        recipient_tax_id,
        related_tranid,
        return_type,
        return_type_description,
        shipaddress,
        shipping_cost,
        shipping_item_id,
        ship_notification_email,
        ship_notification_email_two,
        status,
        tax_reg_id,
        terms_freight_charge,
        terms_insurance_charge,
        terms_of_sale,
        title,
        total_package_weight_in_lbs,
        tranid,
        transaction_extid,
        transaction_id,
        transfer_location_id,
        use_backup_email,
        use_fedex_ship_alert,
        use_ship_notification_email

    from source

)

select * from renamed
