
with source as (

    select * from {{ source('raw_netsuite', 'generic_resources') }}

),

renamed as (

    select
        allow_po_item,
        alternate_billing_email,
        annual_revenue_id,
        ap_priority_id,
        ar_collections,
        ar_follow_up_date,
        ar_specialist_id,
        assess_use_tax_on_billavatax,
        available_on_po,
        bic,
        billing_class_id,
        brn,
        budget_approved,
        buying_time_frame_id,
        channel_tier_id,
        collection_notes,
        collection_status_id,
        collections_notes,
        collections_status_id,
        combo_number_of_employees,
        company_size_id,
        current_access,
        current_annual_bonus_local_cu,
        current_annual_salary_local_c,
        customer_discount,
        customer_number,
        customer_since,
        date_current_bonus_effective,
        date_current_salary_effective,
        date_last_modified,
        dd_file_format_id,
        decision_maker_identified,
        department_id,
        dic,
        direct_debit,
        eft_bill_payment,
        eft_customer_refund_payment,
        eft_file_format_id,
        elastic_cloud_id,
        email_address_for_payment_not,
        employee_number,
        entity_vat_id,
        estimated_budget,
        exclude_from_collections,
        executive_alert_summary,
        exemption_certificate_expirat,
        exemption_certificate_no,
        followup_date,
        foreign_ssn,
        generic_resource_extid,
        generic_resource_id,
        iban,
        ico,
        id_number_in_the_country_of_r,
        id_type_in_the_country_of_r_id,
        is_ar_specialist,
        is_inactive,
        labor_cost,
        last_sales_activity,
        location_id,
        lockout_notice_date,
        lsa_link,
        lsa_link_name,
        marquee_customer,
        ms_active,
        ms_active_date,
        ms_inactive_date,
        multiple_locations,
        okta_id,
        other_software_considered_id,
        parent_company,
        partner_subscription_active,
        party_id,
        percent_complete,
        permissions,
        price,
        reference_classification_id,
        reference_notes,
        reference_status_id,
        regional_vp_id,
        registrant_company_info,
        relationship_id,
        remove_from_approvals_date,
        requires_billing_portal,
        resource_name,
        retained_until,
        salesforce_account_id,
        salesforce_project_id,
        service_hold,
        sfdc_company_id,
        sfdc_contact_id,
        sfdc_ns_customer_id,
        sfdc_segment,
        sod_employee_processing_sta_id,
        sod_status,
        sod_violation_file,
        software_switched_from_id,
        std_work_week_hours,
        subscription_active,
        subsidiary_id,
        super_geo,
        support_level_id,
        sync_to_sfdc,
        tax_contact_first_name,
        tax_contact_id,
        tax_contact_last_name,
        tax_contact_middle_name,
        tax_number,
        third_party_integration_user,
        uen,
        uplift,
        uplift_cap_hidden,
        uplift_cap_type_hidden_id,
        uplift_type_id,
        vat_no__eu,
        vat_registration_no,
        vendor_bank_fees,
        verified_taxexempt,
        webstore_parent_customer_id,
        wfn_employee_no,
        workcalendar_id,
        year_established

    from source

)

select * from renamed
