
with source as (

    select * from {{ source('raw_netsuite', 'service_items_history') }}

),

renamed as (

    select
        avatax_taxcode,
        billings_account_id,
        billings_discount_account_id,
        capacity_id,
        code_of_supply_id,
        commodity_code,
        cost_0,
        cost_category,
        created,
        create_plan_on_event_type,
        date_last_modified,
        date_of_last_transaction,
        description,
        displayname,
        do_not_sync_to_salesforce,
        elastic_cloud_item_id,
        elastic_cloud_item_type_id,
        end_of_life_date,
        end_of_ms_date,
        exempt_from_billing_script,
        expense_account_id,
        featureddescription,
        full_name,
        fx_adjustment_account_id,
        ha_id,
        include_child_subsidiaries,
        income_account_id,
        interco_expense_account_id,
        interco_income_account_id,
        isinactive,
        isonline,
        istaxable,
        is_moss,
        item_category_id,
        item_extid,
        item_id,
        item_revenue_category,
        maintenancesupport_type_id,
        manufacturing_charge_item,
        maximum_quantity_hidden,
        modified,
        mpn,
        ms_pricing_option_id,
        name,
        nature_of_transaction_codes_id,
        node_count,
        offersupport,
        onspecial,
        optout_ms,
        parent_id,
        payment_method_id,
        planned_hours,
        pref_purchase_tax_id,
        pref_sale_tax_id,
        prices_include_tax,
        print_sub_items,
        product_category_id,
        product_family_id,
        product_family_v2_id,
        product_line_id,
        product_type_id,
        purchasedescription,
        quantity_cap_hidden_id,
        quantity_type_id,
        rate,
        region_id,
        related_found_standard_item_id,
        renewals_exclusion,
        renew_with_id,
        replaced_with_id,
        revenue_allocation_group,
        rev_rec_end_date,
        rev_rec_forecast_rule_id,
        rev_rec_rule_id,
        rev_rec_start_date,
        specialsdescription,
        ssd_id,
        storedescription,
        storedetaileddescription,
        storedisplayname,
        subtype,
        supplementary_unit_id,
        supplementary_unit__abberviat,
        term__contract_pricing_type_id,
        training_event_id,
        type_of_goods_id,
        udf1,
        udf2,
        un_number,
        upc_code,
        vendorname,
        vendor_id,
        vsoe_deferral,
        vsoe_delivered,
        vsoe_discount,
        vsoe_price,
        custom_sku,
        embedded_quantity,
        n_606lt_dr_account_id,
        n_606_revenue_account_id,
        n_606_st_dr_account_id,
        ssp_category_id,
        ssp_family_id,
        subject_to_allocation,
        volume_discounted_in_quoting

    from source

)

select * from renamed
