FROM amancevice/superset:2.0.0
# FROM gcr.io/cloud-marketplace/google/superset/postgresql:1.5
# FROM gcr.io/cloud-marketplace/google/superset:1.5

ENV SUPERSET_CONFIG_PATH=/etc/superset/superset_config.py

COPY superset_config.py /etc/superset/superset_config.py
