
with source as (

    select * from {{ source('raw_weblogs', 'weblogs_with_ip_company_view') }}

),

renamed as (

    select
        shipper,
        request,
        referer,
        is_https,
        vary,
        x_cache_hits_b,
        end_request,
        x_cache_b,
        x_served_by_b,
        via,
        req_accept_language,
        begin_request,
        file,
        remote_ip,
        x_cache,
        accept_ranges,
        content_type,
        request_start_epoch_s,
        req_cache_control,
        user_agent,
        x_cache_hits,
        content_length,
        x_timer,
        geoip_continent_name,
        geoip_city_name,
        geoip_country_iso_code,
        geoip_region_name,
        geoip_location_lon,
        geoip_location_lat,
        req_accept_encoding,
        req_pragma,
        content_security_policy,
        strict_transport_security,
        verb,
        http_version,
        cache_control,
        bytes_sent,
        bucket,
        cdn_node,
        x_served_by,
        timestamp,
        response,
        elapsed_usec,
        req_accept,
        etag,
        age,
        id,
        ip,
        lookup_timestamp,
        found,
        domain,
        companyid,
        type,
        fuzzy,
        geoip_city,
        geoip_state,
        geoip_statecode,
        geoip_country,
        geoip_countrycode,
        name,
        indexedat,
        category_industry,
        category_industrygroup,
        category_naicscode,
        category_sector,
        category_siccode,
        category_subindustry,
        crunchbase_handle,
        description,
        domainaliases,
        emailprovider,
        facebook_handle,
        foundedyear,
        geo_city,
        geo_country,
        geo_countrycode,
        geo_lat,
        geo_lng,
        geo_postalcode,
        geo_state,
        geo_statecode,
        geo_streetname,
        geo_streetnumber,
        geo_subpremise,
        identifiers_usein,
        legalname,
        linkedin_handle,
        location,
        logo,
        metrics_alexaglobalrank,
        metrics_alexausrank,
        metrics_annualrevenue,
        metrics_employees,
        metrics_employeesrange,
        metrics_estimatedannualrevenue,
        metrics_fiscalyearend,
        metrics_marketcap,
        metrics_raised,
        parent_domain,
        phone,
        site_emailaddresses,
        site_phonenumbers,
        tags,
        tech,
        ticker,
        timezone,
        twitter_avatar,
        twitter_bio,
        twitter_followers,
        twitter_following,
        twitter_handle,
        twitter_id,
        twitter_location,
        twitter_site,
        utcoffset,
        facebook_likes,
        company_id,
        company_domain,
        company_type

    from source

)

select * from renamed
