
with source as (

    select * from {{ source('raw_salesforce', 'account_clean_info') }}

),

renamed as (

    select
        id,
        _fivetran_synced,
        account_id,
        account_site,
        annual_revenue,
        city,
        cleaned_by_job,
        cleaned_by_user,
        company_name,
        company_status_data_dot_com,
        country,
        created_by_id,
        created_date,
        currency_iso_code,
        dand_bcompany_duns_number,
        data_dot_com_id,
        description,
        duns_number,
        duns_right_match_confidence,
        duns_right_match_grade,
        fax,
        geocode_accuracy,
        industry,
        is_deleted,
        is_different_account_site,
        is_different_annual_revenue,
        is_different_city,
        is_different_company_name,
        is_different_country,
        is_different_country_code,
        is_different_dand_bcompany_duns_number,
        is_different_description,
        is_different_duns_number,
        is_different_fax,
        is_different_industry,
        is_different_naics_code,
        is_different_naics_description,
        is_different_number_of_employees,
        is_different_ownership,
        is_different_phone,
        is_different_postal_code,
        is_different_sic,
        is_different_sic_description,
        is_different_state,
        is_different_state_code,
        is_different_street,
        is_different_ticker_symbol,
        is_different_tradestyle,
        is_different_website,
        is_different_year_started,
        is_flagged_wrong_account_site,
        is_flagged_wrong_address,
        is_flagged_wrong_annual_revenue,
        is_flagged_wrong_company_name,
        is_flagged_wrong_description,
        is_flagged_wrong_duns_number,
        is_flagged_wrong_fax,
        is_flagged_wrong_industry,
        is_flagged_wrong_naics_code,
        is_flagged_wrong_naics_description,
        is_flagged_wrong_number_of_employees,
        is_flagged_wrong_ownership,
        is_flagged_wrong_phone,
        is_flagged_wrong_sic,
        is_flagged_wrong_sic_description,
        is_flagged_wrong_ticker_symbol,
        is_flagged_wrong_tradestyle,
        is_flagged_wrong_website,
        is_flagged_wrong_year_started,
        is_inactive,
        is_reviewed_account_site,
        is_reviewed_address,
        is_reviewed_annual_revenue,
        is_reviewed_company_name,
        is_reviewed_dand_bcompany_duns_number,
        is_reviewed_description,
        is_reviewed_duns_number,
        is_reviewed_fax,
        is_reviewed_industry,
        is_reviewed_naics_code,
        is_reviewed_naics_description,
        is_reviewed_number_of_employees,
        is_reviewed_ownership,
        is_reviewed_phone,
        is_reviewed_sic,
        is_reviewed_sic_description,
        is_reviewed_ticker_symbol,
        is_reviewed_tradestyle,
        is_reviewed_website,
        is_reviewed_year_started,
        last_matched_date,
        last_modified_by_id,
        last_modified_date,
        last_status_changed_by_id,
        last_status_changed_date,
        latitude,
        longitude,
        naics_code,
        naics_description,
        name,
        number_of_employees,
        ownership,
        phone,
        postal_code,
        sic,
        sic_description,
        state,
        street,
        system_modstamp,
        ticker_symbol,
        tradestyle,
        website,
        year_started

    from source

)

select * from renamed
