
with source as (

    select * from {{ source('raw_salesforce', 'pse_forecast_c_history') }}

),

renamed as (

    select
        partitiontime,
        _fivetran_synced,
        created_by_id,
        created_date,
        currency_iso_code,
        id,
        is_deleted,
        last_modified_by_id,
        last_modified_date,
        name,
        pse_best_case_c,
        pse_comments_c,
        pse_commit_c,
        pse_downside_c,
        pse_entered_best_case_c,
        pse_entered_commit_c,
        pse_entered_downside_c,
        pse_entered_forecast_c,
        pse_entered_most_likely_c,
        pse_entered_upside_c,
        pse_entered_worst_case_c,
        pse_forecast_c,
        pse_group_c,
        pse_group_override_this_best_case_c,
        pse_group_override_this_commit_c,
        pse_group_override_this_downside_c,
        pse_group_override_this_forecast_c,
        pse_group_override_this_most_likely_c,
        pse_group_override_this_upside_c,
        pse_group_override_this_worst_case_c,
        pse_most_likely_c,
        pse_override_best_case_c,
        pse_override_commit_c,
        pse_override_downside_c,
        pse_override_forecast_c,
        pse_override_most_likely_c,
        pse_override_upside_c,
        pse_override_worst_case_c,
        pse_plan_c,
        pse_practice_c,
        pse_practice_override_this_best_case_c,
        pse_practice_override_this_commit_c,
        pse_practice_override_this_downside_c,
        pse_practice_override_this_forecast_c,
        pse_practice_override_this_most_likely_c,
        pse_practice_override_this_upside_c,
        pse_practice_override_this_worst_case_c,
        pse_previous_period_best_case_c,
        pse_previous_period_commit_c,
        pse_previous_period_downside_c,
        pse_previous_period_forecast_c,
        pse_previous_period_most_likely_c,
        pse_previous_period_upside_c,
        pse_previous_period_worst_case_c,
        pse_project_c,
        pse_region_c,
        pse_region_override_this_best_case_c,
        pse_region_override_this_commit_c,
        pse_region_override_this_downside_c,
        pse_region_override_this_forecast_c,
        pse_region_override_this_most_likely_c,
        pse_region_override_this_upside_c,
        pse_region_override_this_worst_case_c,
        pse_sub_level_best_case_c,
        pse_sub_level_commit_c,
        pse_sub_level_downside_c,
        pse_sub_level_forecast_c,
        pse_sub_level_most_likely_c,
        pse_sub_level_upside_c,
        pse_sub_level_worst_case_c,
        pse_summary_time_period_c,
        pse_this_best_case_c,
        pse_this_commit_c,
        pse_this_downside_c,
        pse_this_forecast_c,
        pse_this_most_likely_c,
        pse_this_upside_c,
        pse_this_worst_case_c,
        pse_time_period_c,
        pse_upside_c,
        pse_variance_best_case_c,
        pse_variance_commit_c,
        pse_variance_downside_c,
        pse_variance_forecast_c,
        pse_variance_most_likely_c,
        pse_variance_percent_best_case_c,
        pse_variance_percent_commit_c,
        pse_variance_percent_downside_c,
        pse_variance_percent_forecast_c,
        pse_variance_percent_most_likely_c,
        pse_variance_percent_upside_c,
        pse_variance_percent_worst_case_c,
        pse_variance_upside_c,
        pse_variance_worst_case_c,
        pse_worst_case_c,
        system_modstamp

    from source

)

select * from renamed
