
with source as (

    select * from {{ source('raw_salesforce', 'invoice_c') }}

),

renamed as (

    select
        id,
        _fivetran_synced,
        account_c,
        amount_paid_c,
        amount_remaining_c,
        balance_c,
        bill_addr_1_c,
        bill_addr_2_c,
        bill_addr_3_c,
        bill_address_c,
        bill_addressee_c,
        bill_attention_c,
        bill_city_c,
        bill_country_c,
        bill_phone_c,
        bill_state_c,
        bill_zip_c,
        booking_id_c,
        cloud_invoice_id_c,
        cloud_user_id_c,
        created_by_id,
        created_date,
        created_from_c,
        currency_iso_code,
        currency_name_c,
        customer_c,
        deferred_revenue_c,
        discount_amount_c,
        discount_date_c,
        discount_item_c,
        discount_rate_c,
        discount_total_c,
        due_date_c,
        email_c,
        end_date_c,
        est_gross_profit_c,
        est_gross_profit_percent_c,
        exchange_rate_c,
        exclude_commission_c,
        fax_c,
        gift_cert_applied_c,
        individual_c,
        internal_id_c,
        is_deleted,
        is_taxable_c,
        last_activity_date,
        last_modified_by_id,
        last_modified_date,
        last_referenced_date,
        last_viewed_date,
        memo_c,
        message_c,
        name,
        ns_customer_c,
        ns_last_modified_date_c,
        on_credit_hold_c,
        other_ref_number_c,
        owner_id,
        pdf_url_link_c,
        posting_period_c,
        recognized_revenue_c,
        rev_rec_end_date_c,
        rev_rec_on_rev_commitment_c,
        rev_rec_start_date_c,
        revenue_status_c,
        sales_effective_date_c,
        sales_rep_c,
        service_contract_c,
        ship_addr_1_c,
        ship_addr_2_c,
        ship_addr_3_c,
        ship_address_c,
        ship_addressee_c,
        ship_attention_c,
        ship_city_c,
        ship_country_c,
        ship_phone_c,
        ship_state_c,
        ship_zip_c,
        source_c,
        start_date_c,
        status_c,
        subsidiary_c,
        subtotal_c,
        sync_sales_teams_c,
        system_modstamp,
        tax_2_total_c,
        tax_item_c,
        tax_rate_c,
        tax_total_c,
        terms_c,
        total_c,
        total_cost_estimate_c,
        tran_date_c,
        vat_reg_num_c,
        nscustomer_c,
        due_date_days_c,
        contract_c

    from source

)

select * from renamed
