
with source as (

    select * from {{ source('raw_salesforce', 'quote_history') }}

),

renamed as (

    select
        partitiontime,
        id,
        _fivetran_synced,
        account_id,
        additional_city,
        additional_country,
        additional_geocode_accuracy,
        additional_latitude,
        additional_longitude,
        additional_name,
        additional_postal_code,
        additional_state,
        additional_street,
        bill_to_account_c,
        bill_to_account_type_c,
        bill_to_contact_c,
        billing_city,
        billing_country,
        billing_geocode_accuracy,
        billing_latitude,
        billing_longitude,
        billing_name,
        billing_postal_code,
        billing_state,
        billing_street,
        can_create_quote_line_items,
        contact_id,
        contract_id,
        created_by_id,
        created_date,
        currency_iso_code,
        description,
        discount,
        email,
        expiration_date,
        fax,
        grand_total,
        graph_text_c,
        include_plugin_agreement_c,
        is_deleted,
        is_quote_submitted_c,
        is_syncing,
        last_modified_by_id,
        last_modified_date,
        last_referenced_date,
        last_viewed_date,
        master_quote_c,
        name,
        ns_customer_c,
        number_of_nodes_c,
        opportunity_id,
        order_form_pdf_generated_c,
        order_form_tc_c,
        order_form_url_c,
        owner_id,
        phone,
        po_attached_c,
        po_c,
        pricebook_2_id,
        quote_form_comments_c,
        quote_number,
        quote_to_city,
        quote_to_country,
        quote_to_geocode_accuracy,
        quote_to_latitude,
        quote_to_longitude,
        quote_to_name,
        quote_to_postal_code,
        quote_to_state,
        quote_to_street,
        quote_valid_until_c,
        reseller_account_c,
        sales_order_attached_c,
        sales_order_number_c,
        ship_to_contact_c,
        shipping_city,
        shipping_country,
        shipping_geocode_accuracy,
        shipping_handling,
        shipping_latitude,
        shipping_longitude,
        shipping_name,
        shipping_postal_code,
        shipping_state,
        shipping_street,
        special_terms_c,
        status,
        subsidiary_c,
        system_modstamp,
        tax,
        terms_c,
        url_term_c,
        bill_to_account_address_2_c,
        bill_to_account_address_status_c,
        bill_to_account_city_c,
        bill_to_account_country_c,
        bill_to_account_email_c,
        bill_to_account_name_c,
        bill_to_account_postal_code_c,
        bill_to_account_state_c,
        bill_to_account_street_c,
        bill_to_contact_account_name_c,
        change_bill_to_account_address_email_c,
        line_item_count,
        order_form_eula_c,
        order_form_other_ssa_c,
        order_form_ssa_c,
        order_form_support_ssa_c,
        ship_to_contact_account_name_c,
        ship_to_contact_email_c,
        subsidiary_address_1_c,
        subsidiary_address_2_c,
        subsidiary_address_3_c,
        subsidiary_address_4_c,
        subsidiary_address_5_c,
        subsidiary_address_6_c,
        subtotal,
        total_price,
        bypass_lock_validation_c,
        quote_id_18_digits_c

    from source

)

select * from renamed
