
with source as (

    select * from {{ source('raw_salesforce', 'pse_timecard_c') }}

),

renamed as (

    select
        id,
        _fivetran_synced,
        created_by_id,
        created_date,
        currency_iso_code,
        ffrr_exp_revenue_recognition_completed_c,
        ffrrtemplate_c,
        is_deleted,
        last_modified_by_id,
        last_modified_date,
        last_referenced_date,
        last_viewed_date,
        name,
        pse_approved_c,
        pse_approved_for_billing_c,
        pse_approved_for_vendor_payment_c,
        pse_assignment_c,
        pse_bill_date_c,
        pse_bill_transaction_c,
        pse_billable_c,
        pse_billed_c,
        pse_billing_event_item_c,
        pse_billing_hold_c,
        pse_cost_rate_exchange_rate_c,
        pse_cost_transaction_c,
        pse_end_date_c,
        pse_est_vs_actuals_c,
        pse_estimated_time_to_completion_c,
        pse_exclude_from_billing_c,
        pse_external_resource_c,
        pse_friday_hours_c,
        pse_friday_notes_c,
        pse_include_in_financials_c,
        pse_invoice_date_c,
        pse_invoice_number_c,
        pse_invoice_transaction_c,
        pse_invoiced_c,
        pse_location_fri_c,
        pse_location_mon_c,
        pse_location_sat_c,
        pse_location_sun_c,
        pse_location_thu_c,
        pse_location_tue_c,
        pse_location_wed_c,
        pse_milestone_c,
        pse_monday_hours_c,
        pse_monday_notes_c,
        pse_override_cost_group_c,
        pse_override_cost_group_currency_code_c,
        pse_override_cost_practice_c,
        pse_override_cost_practice_currency_code_c,
        pse_override_cost_region_c,
        pse_override_cost_region_currency_code_c,
        pse_override_revenue_group_c,
        pse_override_revenue_group_currency_code_c,
        pse_override_revenue_practice_c,
        pse_override_revenue_practice_currency_code_c,
        pse_override_revenue_region_c,
        pse_override_revenue_region_currency_code_c,
        pse_project_c,
        pse_project_exchange_rate_c,
        pse_resource_c,
        pse_revenue_transaction_c,
        pse_saturday_hours_c,
        pse_saturday_notes_c,
        pse_start_date_c,
        pse_status_c,
        pse_submitted_c,
        pse_sunday_hours_c,
        pse_sunday_notes_c,
        pse_synchronous_update_required_c,
        pse_thursday_hours_c,
        pse_thursday_notes_c,
        pse_time_credited_c,
        pse_time_excluded_c,
        pse_time_transaction_c,
        pse_timecard_header_c,
        pse_timecard_notes_c,
        pse_total_billable_amount_c,
        pse_total_cost_c,
        pse_total_days_worked_c,
        pse_total_hours_c,
        pse_travel_fri_c,
        pse_travel_mon_c,
        pse_travel_sat_c,
        pse_travel_sun_c,
        pse_travel_thu_c,
        pse_travel_tue_c,
        pse_travel_wed_c,
        pse_tuesday_hours_c,
        pse_tuesday_notes_c,
        pse_vendor_invoice_item_c,
        pse_wednesday_hours_c,
        pse_wednesday_notes_c,
        system_modstamp,
        ffrr_exp_bill_rate_c,
        ffrr_exp_resource_name_c,
        project_billing_type_c,
        pse_billing_event_c,
        pse_billing_event_invoiced_c,
        pse_billing_event_released_c,
        pse_billing_event_status_c,
        pse_cost_rate_currency_code_c,
        pse_eligible_for_billing_c,
        pse_travel_c,
        subsidiary_c,
        pse_recognition_method_c

    from source

)

select * from renamed
