
with source as (

    select * from {{ source('raw_salesforce', 'order') }}

),

renamed as (

    select
        id,
        _fivetran_synced,
        account_id,
        activated_by_id,
        activated_date,
        billing_city,
        billing_country,
        billing_geocode_accuracy,
        billing_latitude,
        billing_longitude,
        billing_postal_code,
        billing_state,
        billing_street,
        company_authorized_by_id,
        contract_id,
        created_by_id,
        created_date,
        currency_iso_code,
        customer_authorized_by_id,
        description,
        effective_date,
        end_date,
        is_deleted,
        is_reduction_order,
        last_modified_by_id,
        last_modified_date,
        last_referenced_date,
        last_viewed_date,
        order_number,
        original_order_id,
        owner_id,
        pricebook_2_id,
        shipping_city,
        shipping_country,
        shipping_geocode_accuracy,
        shipping_latitude,
        shipping_longitude,
        shipping_postal_code,
        shipping_state,
        shipping_street,
        status,
        status_code,
        system_modstamp,
        total_amount,
        type,
        sbqq_billing_frequency_c,
        sbqq_contracted_c,
        sbqq_contracting_method_c,
        sbqq_payment_term_c,
        sbqq_price_calc_status_c,
        sbqq_price_calc_status_message_c,
        sbqq_quote_c,
        sbqq_renewal_term_c,
        sbqq_renewal_uplift_rate_c,
        sbqq_order_bookings_c,
        sbqq_tax_amount_c,
        bill_to_contact_id,
        company_authorized_date,
        count_negative_c,
        count_products_c,
        customer_authorized_date,
        locked_c,
        name,
        ogi_c,
        opportunity_id,
        order_group_id_c,
        order_group_id_formula_c,
        order_reference_number,
        original_group_id_c,
        original_group_id_formula_c,
        parent_group_id_c,
        parent_group_id_formula_c,
        parent_opportunity_c,
        parent_order_c,
        po_date,
        po_number,
        quote_id,
        ship_to_contact_id,
        term_c,
        type_c,
        rev_pro_review_required_c,
        rev_pro_status_c,
        channel_c,
        batch_flag_c,
        rc_message_c,
        type_formula_c,
        order_type_c,
        deal_type_c,
        my_c,
        do_not_contract_c,
        contract_c,
        resync_c,
        ne_c,
        ren_c,
        domestic_company_c,
        order_amount_sync_c,
        company_c,
        order_negative_quantity_c,
        tcv_c,
        order_originator_contract_c,
        bill_to_account_c,
        ship_to_contact_c,
        acv_c,
        is_early_renewal_c,
        previous_activated_order_contract_c,
        order_amount_booking_c,
        ns_status_formula_c,
        order_total_c,
        material_rights_c,
        non_standard_payment_terms_c,
        credit_hold_applied_from_quote_c,
        is_full_cancellation_c,
        cancellation_status_c

    from source

)

select * from renamed
