
with source as (

    select * from {{ source('raw_salesforce', 'dand_bcompany_history') }}

),

renamed as (

    select
        partitiontime,
        id,
        _fivetran_synced,
        city,
        company_currency_iso_code,
        country,
        country_access_code,
        created_by_id,
        created_date,
        currency_code,
        currency_iso_code,
        description,
        domestic_ultimate_business_name,
        domestic_ultimate_duns_number,
        duns_number,
        employee_quantity_growth_rate,
        employees_here,
        employees_here_reliability,
        employees_total,
        employees_total_reliability,
        family_members,
        fax,
        fifth_naics,
        fifth_naics_desc,
        fifth_sic,
        fifth_sic_8,
        fifth_sic_8_desc,
        fifth_sic_desc,
        fips_msa_code,
        fips_msa_desc,
        fortune_rank,
        fourth_naics,
        fourth_naics_desc,
        fourth_sic,
        fourth_sic_8,
        fourth_sic_8_desc,
        fourth_sic_desc,
        geo_code_accuracy,
        geocode_accuracy_standard,
        global_ultimate_business_name,
        global_ultimate_duns_number,
        global_ultimate_total_employees,
        import_export_agent,
        included_in_sn_p_500,
        is_deleted,
        last_modified_by_id,
        last_modified_date,
        last_referenced_date,
        last_viewed_date,
        latitude,
        legal_status,
        location_status,
        longitude,
        mailing_city,
        mailing_country,
        mailing_geocode_accuracy,
        mailing_postal_code,
        mailing_state,
        mailing_street,
        marketing_pre_screen,
        marketing_segmentation_cluster,
        minority_owned,
        name,
        national_id,
        national_id_type,
        out_of_business,
        own_or_rent,
        parent_or_hq_business_name,
        parent_or_hq_duns_number,
        phone,
        postal_code,
        premises_measure,
        premises_measure_reliability,
        premises_measure_unit,
        primary_naics,
        primary_naics_desc,
        primary_sic,
        primary_sic_8,
        primary_sic_8_desc,
        primary_sic_desc,
        prior_year_employees,
        prior_year_revenue,
        public_indicator,
        sales_turnover_growth_rate,
        sales_volume,
        sales_volume_reliability,
        second_naics,
        second_naics_desc,
        second_sic,
        second_sic_8,
        second_sic_8_desc,
        second_sic_desc,
        sixth_naics,
        sixth_naics_desc,
        sixth_sic,
        sixth_sic_8,
        sixth_sic_8_desc,
        sixth_sic_desc,
        small_business,
        state,
        stock_exchange,
        stock_symbol,
        street,
        subsidiary,
        system_modstamp,
        third_naics,
        third_naics_desc,
        third_sic,
        third_sic_8,
        third_sic_8_desc,
        third_sic_desc,
        trade_style_1,
        trade_style_2,
        trade_style_3,
        trade_style_4,
        trade_style_5,
        url,
        us_tax_id,
        women_owned,
        year_started

    from source

)

select * from renamed
