
with source as (

    select * from {{ source('raw_salesforce', 'rvpe_rvmember_c') }}

),

renamed as (

    select
        id,
        _fivetran_synced,
        activation_url_c,
        created_by_id,
        created_date,
        currency_iso_code,
        enable_okta_c,
        existing_okta_user_c,
        initial_code_c,
        is_deleted,
        last_activity_date,
        last_modified_by_id,
        last_modified_date,
        last_referenced_date,
        last_viewed_date,
        name,
        owner_id,
        rvpe_address_1_c,
        rvpe_address_2_c,
        rvpe_address_3_c,
        rvpe_agreement_version_c,
        rvpe_city_c,
        rvpe_comments_c,
        rvpe_country_c,
        rvpe_date_agreed_to_terms_c,
        rvpe_email_c,
        rvpe_existing_sfdc_object_id_c,
        rvpe_ext_member_id_c,
        rvpe_fax_c,
        rvpe_first_name_c,
        rvpe_inactive_c,
        rvpe_ipagreed_to_terms_c,
        rvpe_is_test_c,
        rvpe_language_c,
        rvpe_last_name_c,
        rvpe_mobile_c,
        rvpe_phone_c,
        rvpe_rvaccount_c,
        rvpe_rvmember_merge_survivor_c,
        rvpe_rvprogram_c,
        rvpe_salutation_c,
        rvpe_sfcontact_c,
        rvpe_state_province_c,
        rvpe_sync_completed_at_c,
        rvpe_sync_requested_at_c,
        rvpe_title_c,
        rvpe_user_name_c,
        rvpe_web_site_c,
        rvpe_zip_postal_c,
        sso_response_c,
        system_modstamp,
        domain_mis_match_c,
        is_primary_approved_c,
        login_prm_as_user_c,
        reset_password_c,
        rvpe_is_primary_member_c,
        rvpe_sync_needed_c,
        sf_account_c,
        member_domain_c,
        okta_create_override_c,
        quiz_completion_date_c,
        send_existing_user_email_c,
        send_new_user_email_c,
        okta_enabled_c,
        alerting_pass_date_c,
        apm_pass_date_c,
        app_and_site_search_pass_date_c,
        elastic_cloud_enterprise_pass_date_c,
        elastic_search_pass_date_c,
        elastic_search_service_pass_date_c,
        graph_pass_date_c,
        ingest_pass_date_c,
        kibana_pass_date_c,
        logging_pass_date_c,
        machine_learning_pass_date_c,
        metrics_pass_date_c,
        observability_pass_date_c,
        security_analytics_pass_date_c,
        stack_monitoring_operations_pass_date_c,
        stack_security_pass_date_c,
        okta_id_c,
        view_in_okta_c,
        ext_account_id_c

    from source

)

select * from renamed
