
with source as (

    select * from {{ source('raw_salesforce', 'contract_line_item_history') }}

),

renamed as (

    select
        partitiontime,
        id,
        _fivetran_synced,
        asset_id,
        created_by_id,
        created_date,
        currency_iso_code,
        daily_spend_c,
        deal_term_c,
        description,
        discount,
        end_date,
        is_deleted,
        last_modified_by_id,
        last_modified_date,
        last_referenced_date,
        last_viewed_date,
        line_item_number,
        list_price,
        mrr_snapshot_c,
        mtd_spend_c,
        parent_contract_line_item_id,
        pricebook_entry_id,
        product_2_id,
        quantity,
        root_contract_line_item_id,
        sbqqsc_account_c,
        sbqqsc_additional_discount_amount_c,
        sbqqsc_billing_frequency_c,
        sbqqsc_billing_type_c,
        sbqqsc_bundle_c,
        sbqqsc_bundled_c,
        sbqqsc_bundled_quantity_c,
        sbqqsc_charge_type_c,
        sbqqsc_component_discounted_by_package_c,
        sbqqsc_component_subscription_scope_c,
        sbqqsc_customer_price_c,
        sbqqsc_discount_c,
        sbqqsc_discount_schedule_type_c,
        sbqqsc_distributor_discount_c,
        sbqqsc_dynamic_option_id_c,
        sbqqsc_list_price_c,
        sbqqsc_markup_amount_c,
        sbqqsc_markup_rate_c,
        sbqqsc_net_price_c,
        sbqqsc_number_c,
        sbqqsc_option_discount_amount_c,
        sbqqsc_option_discount_c,
        sbqqsc_option_level_c,
        sbqqsc_option_type_c,
        sbqqsc_order_product_c,
        sbqqsc_original_unit_cost_c,
        sbqqsc_partner_discount_c,
        sbqqsc_pricing_method_c,
        sbqqsc_product_c,
        sbqqsc_prorate_multiplier_c,
        sbqqsc_quantity_c,
        sbqqsc_regular_price_c,
        sbqqsc_renewal_price_c,
        sbqqsc_renewal_quantity_c,
        sbqqsc_renewal_uplift_rate_c,
        sbqqsc_renewed_date_c,
        sbqqsc_required_by_id_c,
        sbqqsc_required_by_product_c,
        sbqqsc_revised_subscription_c,
        sbqqsc_root_id_c,
        sbqqsc_segment_end_date_c,
        sbqqsc_segment_index_c,
        sbqqsc_segment_key_c,
        sbqqsc_segment_label_c,
        sbqqsc_segment_quantity_c,
        sbqqsc_segment_start_date_c,
        sbqqsc_segment_uplift_amount_c,
        sbqqsc_segment_uplift_c,
        sbqqsc_special_price_c,
        sbqqsc_subscription_end_date_c,
        sbqqsc_subscription_start_date_c,
        sbqqsc_terminated_date_c,
        sbqqsc_unit_cost_c,
        service_contract_id,
        start_date,
        status,
        subtotal,
        system_modstamp,
        total_price,
        unit_price,
        sbqqsc_dimension_c,
        sbqqsc_discount_schedule_c,
        sbqqsc_original_quote_line_c,
        sbqqsc_product_option_c,
        sbqqsc_quote_line_c,
        sbqqsc_term_discount_schedule_c,
        sbqqsc_contract_number_c,
        sbqqsc_credit_product_id_c,
        sbqqsc_dimension_type_c,
        sbqqsc_product_id_c,
        sbqqsc_product_name_c,
        sbqqsc_renewal_product_id_c,
        sbqqsc_renewal_product_option_id_c,
        sbqqsc_renewal_product_option_product_id_c,
        sbqqsc_renewal_product_option_subscription_pricing_c,
        sbqqsc_start_date_c

    from source

)

select * from renamed
