
with source as (

    select * from {{ source('raw_salesforce', 'escalation_c') }}

),

renamed as (

    select
        id,
        _fivetran_synced,
        action_plan_summary_c,
        additional_comments_c,
        alert_recipients_c,
        changes_since_last_alert_c,
        created_by_id,
        created_date,
        currency_iso_code,
        customer_executive_contact_c,
        date_closed_alert_sent_c,
        days_downgraded_c,
        days_escalated_c,
        escalated_account_c,
        escalation_end_date_c,
        escalation_manager_c,
        escalation_manager_notes_c,
        escalation_start_date_c,
        escalation_trend_c,
        escalations_vp_c,
        exec_action_requested_c,
        exec_escalation_c,
        exec_escalation_reason_c,
        executive_sponsor_c,
        executive_summary_c,
        history_c,
        is_deleted,
        issue_owner_c,
        issue_owner_s_manager_c,
        issue_summary_c,
        key_risk_category_c,
        last_activity_date,
        last_modified_by_id,
        last_modified_date,
        last_referenced_date,
        last_viewed_date,
        lessons_learned_c,
        name,
        next_alert_due_date_c,
        of_days_until_renewal_c,
        original_issue_c,
        owner_id,
        primary_competitor_c,
        primary_product_at_risk_c,
        primary_root_cause_c,
        product_module_at_risk_c,
        rca_outcome_c,
        rca_review_participants_c,
        rca_status_c,
        reason_closed_c,
        reason_de_escalated_c,
        record_type_id,
        red_exit_criteria_c,
        related_case_c,
        related_contract_c,
        renewal_date_c,
        renewal_opportunity_c,
        revenue_at_risk_c,
        risk_detail_c,
        root_cause_summary_c,
        sales_rep_c,
        sales_rep_manager_c,
        sales_vp_c,
        secondary_root_cause_c,
        services_contact_c,
        services_manager_c,
        services_vp_c,
        status_c,
        support_rep_c,
        support_rep_manager_c,
        support_vp_c,
        symptoms_c,
        system_modstamp,
        target_end_date_c,
        watchlist_end_date_c,
        watchlist_start_date_c,
        subscription_c,
        broader_account_risk_c,
        contraction_risk_c,
        contraction_amount_c

    from source

)

select * from renamed
