
with source as (

    select * from {{ source('raw_salesforce', 'deal_support_request_c_history') }}

),

renamed as (

    select
        partitiontime,
        id,
        _fivetran_synced,
        assigned_pm_c,
        choice_of_pm_c,
        core_elasticsearch_date_c,
        core_elasticsearch_ops_date_c,
        course_c,
        course_name_c,
        created_by_id,
        created_date,
        currency_iso_code,
        delivery_method_c,
        desired_training_month_c,
        dsr_opportunity_c,
        elastic_security_analytics_date_c,
        elasticsearch_developer_ii_date_c,
        elasticsearch_engineer_i_c,
        elasticsearch_engineer_ii_c,
        engineering_required_c,
        extension_end_date_c,
        hands_on_workshop_date_c,
        in_person_request_c,
        is_deleted,
        kibana_date_c,
        last_activity_date,
        last_modified_by_id,
        last_modified_date,
        last_referenced_date,
        last_viewed_date,
        level_of_effort_c,
        location_c,
        meeting_request_date_c,
        name,
        number_of_attendees_c,
        number_of_days_requested_c,
        number_of_nodes_requested_c,
        owner_id,
        primary_product_commercial_c,
        primary_product_open_source_c,
        priority_c,
        product_c,
        product_management_required_c,
        reason_for_involvement_c,
        record_type_id,
        related_license_c,
        se_comments_c,
        specialization_date_c,
        status_c,
        system_modstamp,
        training_contact_email_c,
        training_contact_name_c,
        training_location_c,
        trial_dsr_approval_status_c,
        trial_dsr_approver_c,
        type_of_request_c,
        account_c,
        requested_end_date_c,
        sales_rep_c,
        extended_c,
        response_message_c,
        use_case_solution_c,
        already_proposed_consulting_c,
        cm_recommendations_c,
        objectives_c,
        other_use_case_c,
        overview_c,
        sales_notes_c,
        sales_requester_c,
        scoping_notes_c,
        scoping_owner_c,
        special_terms_c,
        combo_area_c,
        combo_routing_region_c,
        opportunity_stage_c,
        opportunity_solution_c,
        sub_extension_approver_c,
        subscription_c,
        opportunity_name_c,
        deal_support_request_link_c,
        subscription_extension_created_c,
        account_geo_c,
        approver_comments_c,
        blended_training_with_consulting_c,
        business_value_assessment_form_complete_c,
        consulting_scoping_email_c,
        custom_sow_c,
        customer_sentiment_c,
        deal_at_risk_c,
        engagement_date_c,
        engagement_type_c,
        field_leadership_priority_c,
        ideal_consulting_start_date_c,
        needed_by_date_c,
        next_approver_c,
        onsite_engagement_required_c,
        opportunity_amount_c,
        opportunity_product_c,
        opportunity_push_counter_c,
        primary_competitor_c,
        primary_engagement_city_c,
        primary_engagement_country_c,
        primary_engagement_state_c,
        primary_engagement_street_c,
        prior_discussions_c,
        remote_only_discount_c,
        request_type_details_c,
        sales_segment_c,
        special_language_considerations_c,
        specific_features_or_capabilities_c,
        stakeholder_linked_in_profiles_c,
        strategic_account_c,
        subcontractors_not_allowed_c,
        successful_outcome_criteria_c,
        unique_circumstances_c,
        value_team_comments_c,
        clearance_c,
        fed_considerations_notes_c

    from source

)

select * from renamed
