
with source as (

    select * from {{ source('raw_salesforce', 'fcrm_fcr_engagement_c_history') }}

),

renamed as (

    select
        partitiontime,
        _fivetran_synced,
        created_by_id,
        created_date,
        currency_iso_code,
        id,
        is_deleted,
        last_modified_by_id,
        last_modified_date,
        name,
        owner_id,
        system_modstamp,
        fcrm_active_response_id_c,
        fcrm_campaign_c,
        fcrm_contact_c,
        fcrm_end_date_c,
        fcrm_fcr_campaign_repeat_parent_c,
        fcrm_fcr_converted_lead_c,
        fcrm_fcr_current_lead_contact_status_c,
        fcrm_fcr_dated_opportunity_amount_c,
        fcrm_fcr_first_owner_assigned_c,
        fcrm_fcr_first_owner_type_c,
        fcrm_fcr_first_owner_worked_c,
        fcrm_fcr_first_queue_assigned_c,
        fcrm_fcr_inquiry_target_c,
        fcrm_fcr_inquiry_target_date_c,
        fcrm_fcr_inquiry_to_mqr_c,
        fcrm_fcr_member_type_on_create_c,
        fcrm_fcr_mqr_to_sar_c,
        fcrm_fcr_name_created_date_c,
        fcrm_fcr_net_new_lead_c,
        fcrm_fcr_non_response_audit_c,
        fcrm_fcr_nurture_timeout_c,
        fcrm_fcr_opportunity_amount_c,
        fcrm_fcr_opportunity_c,
        fcrm_fcr_opportunity_cleared_c,
        fcrm_fcr_opportunity_closed_c,
        fcrm_fcr_opportunity_closed_date_c,
        fcrm_fcr_opportunity_closed_won_c,
        fcrm_fcr_opportunity_count_c,
        fcrm_fcr_opportunity_create_date_c,
        fcrm_fcr_opportunity_created_by_c,
        fcrm_fcr_opportunity_response_error_c,
        fcrm_fcr_opportunity_value_lost_c,
        fcrm_fcr_opportunity_value_won_c,
        fcrm_fcr_original_campaign_c,
        fcrm_fcr_qr_c,
        fcrm_fcr_qr_date_c,
        fcrm_fcr_reactivation_campaign_c,
        fcrm_fcr_reactivation_date_c,
        fcrm_fcr_repeat_count_c,
        fcrm_fcr_response_score_c,
        fcrm_fcr_response_status_c,
        fcrm_fcr_revenue_timestamp_c,
        fcrm_fcr_sar_c,
        fcrm_fcr_sar_date_c,
        fcrm_fcr_sar_owner_c,
        fcrm_fcr_sar_to_sqr_c,
        fcrm_fcr_sqr_c,
        fcrm_fcr_sqr_date_c,
        fcrm_fcr_sqr_to_closed_won_c,
        fcrm_fcr_sqr_won_c,
        fcrm_fcr_status_age_c,
        fcrm_fcr_status_last_set_c,
        fcrm_fcr_tqr_c,
        fcrm_first_responded_date_c,
        fcrm_lead_c,
        fcrm_opportunity_value_open_c,
        fcrm_responded_c,
        fcrm_start_date_c,
        fcrm_status_c

    from source

)

select * from renamed
