
with source as (

    select * from {{ source('raw_salesforce', 'pse_project_task_c') }}

),

renamed as (

    select
        id,
        _fivetran_synced,
        created_by_id,
        created_date,
        currency_iso_code,
        is_deleted,
        last_activity_date,
        last_modified_by_id,
        last_modified_date,
        last_referenced_date,
        last_viewed_date,
        name,
        owner_id,
        pse_actual_end_date_time_c,
        pse_actual_hours_c,
        pse_actual_start_date_time_c,
        pse_assigned_resources_c,
        pse_assigned_resources_long_c,
        pse_blocked_c,
        pse_closed_for_time_entry_c,
        pse_completed_c,
        pse_description_c,
        pse_do_not_auto_update_parents_c,
        pse_do_not_auto_update_this_task_c,
        pse_duration_unit_c,
        pse_end_date_time_c,
        pse_estimated_hours_c,
        pse_estimated_time_to_completion_c,
        pse_external_task_id_c,
        pse_flag_information_c,
        pse_flag_task_dates_no_coverage_c,
        pse_flag_task_dates_partial_coverage_c,
        pse_flag_task_end_milestone_bounds_c,
        pse_flag_task_end_project_bounds_c,
        pse_flag_task_hours_no_coverage_c,
        pse_flag_task_hours_partial_coverage_c,
        pse_flag_task_start_milestone_bounds_c,
        pse_flag_task_start_project_bounds_c,
        pse_hierarchy_depth_c,
        pse_long_description_c,
        pse_milestone_c,
        pse_notes_c,
        pse_order_c,
        pse_parent_task_c,
        pse_percent_complete_points_c,
        pse_percent_complete_tasks_c,
        pse_points_baseline_c,
        pse_points_c,
        pse_points_complete_c,
        pse_priority_c,
        pse_project_c,
        pse_start_date_time_c,
        pse_started_c,
        pse_status_c,
        pse_summary_c,
        pse_task_id_chain_c,
        pse_task_key_c,
        pse_task_key_chain_c,
        pse_task_name_chain_c,
        pse_task_name_chain_long_c,
        pse_task_number_c,
        pse_top_level_parent_task_c,
        pse_wbs_element_number_c,
        pse_work_remaining_c,
        system_modstamp,
        pse_actual_end_date_c,
        pse_actual_start_date_c,
        pse_end_date_c,
        pse_hours_remaining_c,
        pse_number_of_assignments_c,
        pse_parent_task_end_date_c,
        pse_parent_task_end_date_time_c,
        pse_parent_task_start_date_c,
        pse_parent_task_start_date_time_c,
        pse_percent_complete_hours_c,
        pse_points_remaining_c,
        pse_projected_hours_c,
        pse_start_date_c,
        pse_timecard_hours_c,
        record_type_id,
        time_zone_c,
        user_is_resource_c,
        vfp_remote_c,
        vfp_resource_c,
        pse_work_calendar_c,
        pse_synchronize_milestone_and_task_c,
        pse_sync_with_jira_c,
        pse_jira_issue_type_category_c,
        pse_jira_correlation_id_c,
        pse_jira_issue_type_c

    from source

)

select * from renamed
