
with source as (

    select * from {{ source('raw_salesforce', 'fstr_process_composer_settings_c_history') }}

),

renamed as (

    select
        partitiontime,
        id,
        _fivetran_synced,
        created_by_id,
        created_date,
        currency_iso_code,
        fstr_account_match_field_c,
        fstr_allow_case_close_from_process_completion_c,
        fstr_allowed_assignee_types_c,
        fstr_allowed_namespaces_c,
        fstr_automatic_chatter_posting_c,
        fstr_chatter_post_name_field_c,
        fstr_chatter_team_selection_c,
        fstr_closed_status_values_c,
        fstr_color_code_external_step_c,
        fstr_color_code_internal_step_c,
        fstr_color_code_overdue_status_c,
        fstr_custom_process_group_account_field_c,
        fstr_custom_process_group_end_date_c,
        fstr_custom_process_group_name_c,
        fstr_custom_process_group_start_date_c,
        fstr_custom_sharing_method_c,
        fstr_default_step_assignee_type_c,
        fstr_default_step_assignee_user_c,
        fstr_default_step_object_c,
        fstr_disable_account_trigger_c,
        fstr_disable_business_process_trigger_c,
        fstr_disable_campaign_trigger_c,
        fstr_disable_case_trigger_c,
        fstr_disable_contact_trigger_c,
        fstr_disable_contract_trigger_c,
        fstr_disable_edit_delete_of_closed_steps_c,
        fstr_disable_event_trigger_c,
        fstr_disable_export_c,
        fstr_disable_lead_trigger_c,
        fstr_disable_non_task_step_assignee_options_c,
        fstr_disable_opportunity_trigger_c,
        fstr_disable_process_task_trigger_c,
        fstr_disable_process_team_duplicate_check_c,
        fstr_disable_record_matches_initiator_option_c,
        fstr_disable_set_account_lookup_c,
        fstr_disable_task_trigger_c,
        fstr_disable_user_deactivation_checks_c,
        fstr_disable_web_service_callout_c,
        fstr_document_merge_use_qa_c,
        fstr_due_date_skip_non_working_days_c,
        fstr_enable_delete_override_c,
        fstr_enable_doc_merge_logging_c,
        fstr_external_step_label_c,
        fstr_include_non_closed_statuses_c,
        fstr_initiator_custom_object_account_field_c,
        fstr_initiator_custom_object_contact_field_c,
        fstr_initiator_custom_object_overflow_acct_c,
        fstr_initiator_custom_object_overflow_cont_c,
        fstr_initiator_custom_objects_c,
        fstr_initiator_custom_objects_overflow_c,
        fstr_internal_step_label_c,
        fstr_is_process_summary_enabled_c,
        fstr_notification_email_address_c,
        fstr_process_archive_objects_c,
        fstr_process_objects_c,
        fstr_process_record_match_initiators_batch_size_c,
        fstr_process_summary_show_tasks_c,
        fstr_process_team_member_match_field_c,
        fstr_public_notes_field_c,
        fstr_recurring_bp_show_all_record_types_c,
        fstr_roles_to_mention_in_chatter_post_c,
        fstr_send_recurring_batch_job_emails_c,
        fstr_show_notes_and_attachments_on_step_page_c,
        fstr_sms_notifications_enabled_c,
        fstr_step_objects_c,
        fstr_task_custom_lookup_related_to_passthrough_c,
        fstr_task_custom_process_object_lookup_c,
        fstr_text_link_url_c,
        fstr_text_notification_message_c,
        fstr_text_reassignment_message_c,
        fstr_twilio_account_sid_c,
        fstr_twilio_application_sid_c,
        fstr_twilio_auth_token_c,
        fstr_twilio_from_number_c,
        fstr_use_qa_c,
        fstr_version_c,
        fstr_virtual_step_objects_2_c,
        fstr_virtual_step_objects_c,
        fstr_virtual_steps_recalculate_c,
        is_deleted,
        last_modified_by_id,
        last_modified_date,
        name,
        setup_owner_id,
        system_modstamp,
        fstr_composer_certificate_name_c,
        fstr_composer_endpoint_c,
        fstr_default_composer_url_c,
        fstr_enable_platform_event_logging_c,
        fstr_enable_rpa_logging_c,
        fstr_show_advanced_step_settings_c,
        fstr_has_gone_through_setup_c

    from source

)

select * from renamed
