
with source as (

    select * from {{ source('raw_salesforce', 'fferpcore_billing_document_c') }}

),

renamed as (

    select
        id,
        _fivetran_synced,
        created_by_id,
        created_date,
        currency_iso_code,
        fferpcore_account_c,
        fferpcore_analysis_item_1_c,
        fferpcore_analysis_item_2_c,
        fferpcore_analysis_item_3_c,
        fferpcore_analysis_item_4_c,
        fferpcore_billing_account_name_c,
        fferpcore_billing_city_c,
        fferpcore_billing_country_c,
        fferpcore_billing_postal_code_c,
        fferpcore_billing_state_c,
        fferpcore_billing_street_c,
        fferpcore_company_c,
        fferpcore_completion_process_tracking_c,
        fferpcore_customer_reference_c,
        fferpcore_date_issued_c,
        fferpcore_description_c,
        fferpcore_discount_total_c,
        fferpcore_document_date_c,
        fferpcore_document_due_date_c,
        fferpcore_document_status_c,
        fferpcore_document_total_c,
        fferpcore_document_type_c,
        fferpcore_document_type_prefix_c,
        fferpcore_external_document_number_c,
        fferpcore_footer_text_c,
        fferpcore_header_text_c,
        fferpcore_is_billing_address_validated_c,
        fferpcore_is_complete_c,
        fferpcore_is_shipping_address_validated_c,
        fferpcore_net_total_c,
        fferpcore_number_of_billing_document_line_items_c,
        fferpcore_related_document_c,
        fferpcore_reporting_document_total_c,
        fferpcore_shipping_account_name_c,
        fferpcore_shipping_city_c,
        fferpcore_shipping_country_c,
        fferpcore_shipping_postal_code_c,
        fferpcore_shipping_state_c,
        fferpcore_shipping_street_c,
        fferpcore_tax_value_total_c,
        fferpcore_validated_billing_city_c,
        fferpcore_validated_billing_country_c,
        fferpcore_validated_billing_postal_code_c,
        fferpcore_validated_billing_state_c,
        fferpcore_validated_billing_street_c,
        fferpcore_validated_shipping_city_c,
        fferpcore_validated_shipping_country_c,
        fferpcore_validated_shipping_postal_code_c,
        fferpcore_validated_shipping_state_c,
        fferpcore_validated_shipping_street_c,
        is_deleted,
        last_activity_date,
        last_modified_by_id,
        last_modified_date,
        last_referenced_date,
        last_viewed_date,
        name,
        owner_id,
        pse_billing_event_correlation_id_c,
        system_modstamp,
        fferpcore_is_tax_calculated_c,
        fferpcore_credit_note_reason_c,
        fferpcore_processing_tax_details_c,
        fferpcore_external_tax_status_c,
        fferpcore_document_source_c,
        fferpcore_engagement_c,
        fferpcore_allow_rebilling_c,
        fferpcore_tax_point_date_c

    from source

)

select * from renamed
