
with source as (

    select * from {{ source('raw_salesforce', 'asset_history') }}

),

renamed as (

    select
        partitiontime,
        id,
        _fivetran_synced,
        account_id,
        contact_id,
        created_by_id,
        created_date,
        currency_iso_code,
        description,
        install_date,
        is_competitor_product,
        is_deleted,
        last_modified_by_id,
        last_modified_date,
        last_referenced_date,
        last_viewed_date,
        name,
        parent_id,
        price,
        product_2_id,
        purchase_date,
        quantity,
        root_asset_id,
        sbqqsc_current_contract_line_item_c,
        sbqqsc_required_by_line_item_c,
        serial_number,
        status,
        stock_keeping_unit,
        system_modstamp,
        usage_end_date,
        sbqq_additional_discount_amount_c,
        sbqq_billing_frequency_c,
        sbqq_billing_type_c,
        sbqq_bundle_c,
        sbqq_bundled_c,
        sbqq_bundled_quantity_c,
        sbqq_charge_type_c,
        sbqq_combine_key_c,
        sbqq_component_discounted_by_package_c,
        sbqq_current_subscription_c,
        sbqq_discount_c,
        sbqq_discount_schedule_c,
        sbqq_discount_schedule_type_c,
        sbqq_distributor_discount_c,
        sbqq_dynamic_option_id_c,
        sbqq_from_service_cloud_c,
        sbqq_latest_quote_line_c,
        sbqq_list_price_c,
        sbqq_markup_amount_c,
        sbqq_markup_rate_c,
        sbqq_number_c,
        sbqq_option_discount_amount_c,
        sbqq_option_discount_c,
        sbqq_option_level_c,
        sbqq_option_type_c,
        sbqq_order_product_c,
        sbqq_original_unit_cost_c,
        sbqq_partner_discount_c,
        sbqq_pricing_method_c,
        sbqq_product_option_c,
        sbqq_quote_line_c,
        sbqq_regular_price_c,
        sbqq_renewal_uplift_rate_c,
        sbqq_required_by_asset_c,
        sbqq_required_by_id_c,
        sbqq_required_by_product_c,
        sbqq_required_by_subscription_c,
        sbqq_revised_asset_c,
        sbqq_root_asset_c,
        sbqq_root_id_c,
        sbqq_segment_index_c,
        sbqq_segment_key_c,
        sbqq_segment_label_c,
        sbqq_subscription_c,
        sbqq_subscription_end_date_c,
        sbqq_subscription_quote_line_c,
        sbqq_subscription_start_date_c,
        sbqq_term_discount_schedule_c,
        sbqq_unit_cost_c,
        sbqq_virtual_asset_c,
        sbqq_credit_product_id_c,
        sbqq_dimension_c,
        asset_level,
        asset_provided_by_id,
        asset_serviced_by_id,
        digital_asset_status,
        external_identifier,
        is_internal,
        location_id,
        manufacture_date,
        product_code,
        product_description,
        product_family,
        sbqq_package_product_code_c,
        sbqq_package_product_description_c,
        sbqq_price_dimension_c,
        status_reason,
        uuid

    from source

)

select * from renamed
