
with source as (

    select * from {{ source('raw_salesforce', 'rvpe_rvaccount_c_history') }}

),

renamed as (

    select
        partitiontime,
        id,
        _fivetran_synced,
        agreement_tier_c,
        agreement_type_c,
        created_by_id,
        created_date,
        currency_iso_code,
        current_pipeline_opportunities_c,
        how_do_you_see_elastic_adding_value_c,
        how_do_you_see_your_company_adding_value_c,
        how_many_engagements_c,
        industries_c,
        is_deleted,
        last_activity_date,
        last_modified_by_id,
        last_modified_date,
        last_referenced_date,
        last_viewed_date,
        markets_served_c,
        name,
        number_of_employees_c,
        other_partnership_area_of_interest_c,
        owner_id,
        partner_application_status_c,
        partnerships_with_other_software_vendors_c,
        primary_business_model_other_details_c,
        primary_customer_base_public_sector_c,
        primary_partnership_area_of_interest_c,
        primary_vertical_c,
        rate_team_s_level_of_understanding_c,
        rpl_c,
        rvpe_address_1_c,
        rvpe_address_2_c,
        rvpe_address_3_c,
        rvpe_city_c,
        rvpe_comments_c,
        rvpe_country_c,
        rvpe_existing_sfdc_object_id_c,
        rvpe_ext_account_id_c,
        rvpe_fax_1_c,
        rvpe_fax_2_c,
        rvpe_inactive_c,
        rvpe_is_test_c,
        rvpe_partner_level_c,
        rvpe_phone_1_c,
        rvpe_phone_2_c,
        rvpe_primary_business_type_c,
        rvpe_rvaccount_merge_survivor_c,
        rvpe_rvparent_account_c,
        rvpe_rvprimary_member_c,
        rvpe_rvprogram_c,
        rvpe_sfaccount_c,
        rvpe_site_c,
        rvpe_state_province_c,
        rvpe_sync_completed_at_c,
        rvpe_sync_requested_at_c,
        rvpe_web_site_c,
        rvpe_zip_postal_c,
        saas_or_self_managed_c,
        system_modstamp,
        use_case_c,
        use_case_details_c,
        what_is_your_primary_business_model_c,
        primary_member_name_c,
        rvpe_hierarchical_name_c,
        rvpe_sync_needed_c,
        primary_domain_c,
        primary_email_c,
        primary_member_email_c,
        primary_rvmember_id_c,
        view_in_prm_c,
        primary_domain_override_c,
        account_partner_agreement_type_c,
        rvpe_long_name_c,
        partner_level_c,
        partner_priority_c,
        partner_type_formula_c,
        partner_rest_of_world_c,
        partner_types_c,
        accreditations_c,
        amount_of_influence_revenue_closed_c,
        certifications_c,
        dollar_amount_of_partner_sourced_revenue_c,
        dollar_amount_of_transactional_revenue_c,
        quantity_of_influenced_deals_c,
        quantity_of_transactional_deals_closed_c,
        partner_manager_c,
        partner_manager_full_name_c

    from source

)

select * from renamed
