
with source as (

    select * from {{ source('raw_salesforce', 'pse_resource_request_c') }}

),

renamed as (

    select
        id,
        _fivetran_synced,
        created_by_id,
        created_date,
        currency_iso_code,
        is_deleted,
        last_activity_date,
        last_modified_by_id,
        last_modified_date,
        last_referenced_date,
        last_viewed_date,
        name,
        owner_id,
        pse_assignment_c,
        pse_average_cost_rate_currency_code_c,
        pse_average_cost_rate_number_c,
        pse_eligible_for_schedule_recalculation_c,
        pse_end_date_c,
        pse_exclude_from_planners_c,
        pse_group_c,
        pse_latitude_psa_c,
        pse_longitude_psa_c,
        pse_milestone_c,
        pse_notes_c,
        pse_opportunity_c,
        pse_percent_allocated_c,
        pse_planned_bill_rate_c,
        pse_practice_c,
        pse_preferred_schedule_c,
        pse_primary_skill_certification_c,
        pse_primary_skill_minimum_rating_c,
        pse_project_c,
        pse_rate_card_c,
        pse_region_c,
        pse_related_resource_request_staffed_on_c,
        pse_request_priority_c,
        pse_requested_bill_rate_c,
        pse_resource_c,
        pse_resource_held_c,
        pse_resource_request_name_c,
        pse_resource_request_set_c,
        pse_resource_role_c,
        pse_sow_hours_c,
        pse_staffed_related_resource_request_c,
        pse_staffer_approval_required_c,
        pse_staffer_resource_c,
        pse_start_date_c,
        pse_status_c,
        pse_suggested_bill_rate_currency_code_c,
        pse_suggested_bill_rate_number_c,
        pse_update_related_resource_requests_c,
        pse_work_city_psa_c,
        pse_work_country_psa_c,
        pse_work_postal_code_psa_c,
        pse_work_state_psa_c,
        pse_work_street_psa_c,
        required_resource_c,
        system_modstamp,
        psa_report_project_name_c,
        pse_account_c,
        pse_account_id_c,
        pse_account_link_c,
        pse_average_cost_rate_c,
        pse_opportunity_probability_c,
        pse_request_billable_amount_c,
        pse_suggested_bill_rate_c,
        pse_exclude_from_utilization_c,
        psaws_project_manager_is_current_user_c,
        psaws_close_to_start_date_c,
        psaws_requires_staffing_c,
        vfp_rr_color_c,
        pse_utilization_run_c,
        pse_information_for_prospective_candidates_c,
        pse_allow_candidates_to_self_nominate_c,
        pse_self_nomination_deadline_c

    from source

)

select * from renamed
