
with source as (

    select * from {{ source('raw_salesforce', 'fcrm_fcr_influence_detail_c_history') }}

),

renamed as (

    select
        partitiontime,
        id,
        _fivetran_synced,
        campaign_type_c,
        created_by_id,
        created_date,
        currency_iso_code,
        current_opportunity_stage_c,
        fcrm_account_c,
        fcrm_admin_update_counter_c,
        fcrm_campaign_c,
        fcrm_cascade_parent_campaign_c,
        fcrm_closed_op_revenue_model_1_c,
        fcrm_closed_op_revenue_model_2_c,
        fcrm_closed_op_revenue_model_3_c,
        fcrm_contact_c,
        fcrm_has_influence_model_1_c,
        fcrm_has_influence_model_2_c,
        fcrm_has_influence_model_3_c,
        fcrm_inquiry_target_c,
        fcrm_inquiry_target_date_c,
        fcrm_lead_c,
        fcrm_lost_op_revenue_model_1_c,
        fcrm_lost_op_revenue_model_2_c,
        fcrm_lost_op_revenue_model_3_c,
        fcrm_member_type_on_create_c,
        fcrm_name_created_date_c,
        fcrm_net_new_name_c,
        fcrm_next_opportunity_stage_c,
        fcrm_open_op_revenue_model_1_c,
        fcrm_open_op_revenue_model_2_c,
        fcrm_open_op_revenue_model_3_c,
        fcrm_opportunity_c,
        fcrm_opportunity_stage_c,
        fcrm_opportunity_stage_date_c,
        fcrm_opportunity_stage_progression_date_c,
        fcrm_qr_c,
        fcrm_qr_date_c,
        fcrm_response_date_c,
        fcrm_response_id_c,
        fcrm_response_status_c,
        fcrm_sar_c,
        fcrm_sar_date_c,
        fcrm_sqr_c,
        fcrm_sqr_date_c,
        fcrm_sqr_won_c,
        fcrm_test_record_c,
        fcrm_unique_id_c,
        fcrm_unix_op_close_time_c,
        fcrm_unix_op_create_time_c,
        industry_c,
        is_deleted,
        last_modified_by_id,
        last_modified_date,
        lead_2_c,
        lead_date_c,
        marketing_campaign_c,
        marketing_external_combo_c,
        marketing_internal_combo_c,
        marketing_master_combo_c,
        marketing_medium_c,
        marketing_region_c,
        marketing_source_c,
        member_status_2_c,
        mql_c,
        mql_date_c,
        name,
        opportunity_record_type_c,
        owner_id,
        products_c,
        promo_code_c,
        sub_campaign_type_c,
        system_modstamp,
        target_segment_c,
        cloud_trial_by_invite_c,
        opportunity_close_date_c,
        opportunity_record_type_formula_c,
        fcrm_opportunity_timeframe_c,
        fcrm_tipping_point_response_c,
        pubsec_account_type_c,
        fcrm_days_before_opportunity_create_c,
        campaign_type_formula_c,
        opportunity_name_c,
        current_opportunity_stage_formula_c,
        fcrm_total_op_revenue_model_3_c,
        fcrm_total_op_revenue_model_2_c,
        fcrm_total_op_revenue_model_1_c,
        fcrm_count_c,
        activity_level_c,
        cloud_trial_length_c,
        data_quality_level_c,
        form_fill_referrer_c,
        fcrm_estimated_cost_model_1_c,
        fcrm_estimated_cost_model_2_c,
        fcrm_estimated_cost_model_3_c,
        fcrm_member_status_c

    from source

)

select * from renamed
