
with source as (

    select * from {{ source('raw_salesforce', 'pse_timecard_header_c') }}

),

renamed as (

    select
        id,
        _fivetran_synced,
        created_by_id,
        created_date,
        currency_iso_code,
        is_deleted,
        last_activity_date,
        last_modified_by_id,
        last_modified_date,
        last_referenced_date,
        last_viewed_date,
        name,
        owner_id,
        pse_additional_notes_c,
        pse_admin_global_edit_c,
        pse_approved_c,
        pse_approver_c,
        pse_assignment_c,
        pse_audit_notes_c,
        pse_audit_notes_history_c,
        pse_bill_rate_c,
        pse_bill_rate_defaulted_from_milestone_c,
        pse_billable_c,
        pse_billed_c,
        pse_cost_rate_amount_c,
        pse_cost_rate_currency_code_c,
        pse_cost_rate_exchange_rate_c,
        pse_daily_bill_rate_c,
        pse_daily_cost_rate_c,
        pse_days_worked_override_c,
        pse_disable_approval_auto_submit_c,
        pse_end_date_c,
        pse_estimated_time_to_completion_c,
        pse_exclude_from_billing_c,
        pse_exclude_from_daily_maximum_c,
        pse_external_resource_c,
        pse_friday_hours_c,
        pse_friday_notes_c,
        pse_include_in_financials_c,
        pse_invoiced_c,
        pse_location_fri_c,
        pse_location_mon_c,
        pse_location_sat_c,
        pse_location_sun_c,
        pse_location_thu_c,
        pse_location_tue_c,
        pse_location_wed_c,
        pse_milestone_c,
        pse_monday_hours_c,
        pse_monday_notes_c,
        pse_override_cost_group_c,
        pse_override_cost_practice_c,
        pse_override_cost_region_c,
        pse_override_revenue_group_c,
        pse_override_revenue_practice_c,
        pse_override_revenue_region_c,
        pse_primary_location_c,
        pse_primary_project_location_c,
        pse_project_c,
        pse_project_exchange_rate_c,
        pse_project_location_fri_c,
        pse_project_location_mon_c,
        pse_project_location_sat_c,
        pse_project_location_sun_c,
        pse_project_location_thu_c,
        pse_project_location_tue_c,
        pse_project_location_wed_c,
        pse_project_methodology_c,
        pse_project_methodology_object_c,
        pse_project_phase_c,
        pse_project_phase_object_c,
        pse_resource_c,
        pse_saturday_hours_c,
        pse_saturday_notes_c,
        pse_start_date_c,
        pse_status_c,
        pse_submitted_c,
        pse_sunday_hours_c,
        pse_sunday_notes_c,
        pse_thursday_hours_c,
        pse_thursday_notes_c,
        pse_time_credited_c,
        pse_time_excluded_c,
        pse_timecard_notes_c,
        pse_timecard_ui_save_submit_needed_c,
        pse_travel_fri_c,
        pse_travel_mon_c,
        pse_travel_sat_c,
        pse_travel_sun_c,
        pse_travel_thu_c,
        pse_travel_tue_c,
        pse_travel_wed_c,
        pse_tuesday_hours_c,
        pse_tuesday_notes_c,
        pse_wednesday_hours_c,
        pse_wednesday_notes_c,
        system_modstamp,
        project_billing_type_c,
        pse_cost_rate_c,
        pse_hours_to_days_rule_assignment_c,
        pse_hours_to_days_rule_project_c,
        pse_project_task_hours_c,
        pse_total_billable_amount_c,
        pse_total_cost_c,
        pse_total_days_worked_advanced_c,
        pse_total_days_worked_c,
        pse_total_hours_c,
        pse_travel_week_c,
        timecard_split_id_18_digit_c,
        pse_exclude_from_utilization_c,
        psaws_is_resource_current_user_c,
        vfp_days_since_submission_c

    from source

)

select * from renamed
