
with source as (

    select * from {{ source('raw_salesforce', 'fstr_pce_step_c_history') }}

),

renamed as (

    select
        partitiontime,
        id,
        _fivetran_synced,
        created_by_id,
        created_date,
        currency_iso_code,
        fstr_approval_status_c,
        fstr_approval_step_c,
        fstr_assignee_c,
        fstr_assignee_type_c,
        fstr_chatter_notification_c,
        fstr_chatter_notification_message_c,
        fstr_checklist_c,
        fstr_classification_c,
        fstr_clause_bundle_sort_order_c,
        fstr_collaborate_solution_c,
        fstr_composer_email_template_id_c,
        fstr_composer_email_template_name_c,
        fstr_composer_solution_c,
        fstr_composer_solution_name_c,
        fstr_copy_subject_from_parent_process_object_c,
        fstr_create_if_parent_c,
        fstr_create_if_parent_canceled_c,
        fstr_create_if_parent_completed_c,
        fstr_create_on_first_match_only_c,
        fstr_create_with_status_c,
        fstr_cumulative_date_adjustment_c,
        fstr_default_assignee_user_c,
        fstr_definition_c,
        fstr_delay_creation_base_date_c,
        fstr_delay_creation_c,
        fstr_delay_creation_date_adjustment_c,
        fstr_delay_creation_date_field_c,
        fstr_delay_creation_date_field_name_c,
        fstr_delay_creation_time_c,
        fstr_description_c,
        fstr_do_not_reopen_c,
        fstr_document_merge_c,
        fstr_due_date_adjustment_base_date_c,
        fstr_due_date_adjustment_c,
        fstr_due_date_adjustment_date_field_c,
        fstr_due_date_adjustment_date_field_name_c,
        fstr_email_additional_to_c,
        fstr_email_alert_c,
        fstr_email_bcc_c,
        fstr_email_from_c,
        fstr_email_from_name_c,
        fstr_email_template_id_c,
        fstr_email_template_name_c,
        fstr_email_to_c,
        fstr_email_to_target_c,
        fstr_event_placeholder_c,
        fstr_event_sub_type_c,
        fstr_field_update_c,
        fstr_field_validation_message_c,
        fstr_generate_email_notification_c,
        fstr_generate_sms_notification_c,
        fstr_generate_step_c,
        fstr_go_back_to_stage_c,
        fstr_go_back_to_step_c,
        fstr_ignore_in_stage_completion_c,
        fstr_is_deletable_c,
        fstr_merge_button_id_c,
        fstr_merge_button_name_c,
        fstr_merge_product_c,
        fstr_merge_product_name_c,
        fstr_merge_result_file_name_prefix_c,
        fstr_merge_submit_esign_c,
        fstr_merge_template_id_c,
        fstr_merge_template_name_c,
        fstr_number_of_dependent_fields_c,
        fstr_number_of_field_validations_c,
        fstr_number_of_reevaluation_criteria_c,
        fstr_obj_data_1_c,
        fstr_obj_data_2_c,
        fstr_object_record_type_to_create_c,
        fstr_object_record_type_to_create_name_c,
        fstr_object_type_to_create_c,
        fstr_object_type_to_create_name_c,
        fstr_output_to_pdf_c,
        fstr_parent_object_id_c,
        fstr_parent_object_lookup_field_c,
        fstr_parent_stage_c,
        fstr_parent_step_c,
        fstr_pce_definition_to_execute_c,
        fstr_perform_callout_on_c,
        fstr_queue_c,
        fstr_reassignment_count_c,
        fstr_reevaluate_when_c,
        fstr_rejection_action_c,
        fstr_rejection_status_c,
        fstr_role_c,
        fstr_send_grid_email_sender_c,
        fstr_send_grid_email_template_id_c,
        fstr_send_grid_email_template_name_c,
        fstr_skip_if_past_due_c,
        fstr_stage_c,
        fstr_status_managed_by_c,
        fstr_step_creation_custom_criteria_c,
        fstr_step_type_c,
        fstr_stop_process_if_status_set_to_c,
        fstr_task_comment_c,
        fstr_user_field_c,
        fstr_user_field_name_c,
        fstr_web_service_callout_body_c,
        fstr_web_service_callout_c,
        fstr_web_service_callout_headers_c,
        fstr_web_service_callout_method_c,
        fstr_web_service_callout_url_c,
        is_deleted,
        last_modified_by_id,
        last_modified_date,
        name,
        system_modstamp

    from source

)

select * from renamed
