
with source as (

    select * from {{ source('raw_salesforce', 'ffrr_settings_c') }}

),

renamed as (

    select
        id,
        _fivetran_synced,
        created_by_id,
        created_date,
        currency_iso_code,
        ffrr_account_name_c,
        ffrr_active_field_c,
        ffrr_active_value_c,
        ffrr_actual_vs_forecast_relationship_c,
        ffrr_amortized_to_date_value_c,
        ffrr_balance_sheet_account_c,
        ffrr_billed_to_date_c,
        ffrr_chain_id_c,
        ffrr_completed_field_c,
        ffrr_completed_value_c,
        ffrr_cost_balance_sheet_account_c,
        ffrr_cost_center_c,
        ffrr_cost_cost_center_c,
        ffrr_cost_income_statement_account_c,
        ffrr_cost_rate_c,
        ffrr_cost_total_units_c,
        ffrr_currency_c,
        ffrr_default_field_mapping_definition_c,
        ffrr_description_c,
        ffrr_end_date_c,
        ffrr_filter_1_c,
        ffrr_filter_2_c,
        ffrr_filter_3_c,
        ffrr_fixed_balance_sheet_account_code_c,
        ffrr_fixed_cost_balance_sheet_account_code_c,
        ffrr_fixed_cost_center_code_c,
        ffrr_fixed_cost_cost_center_code_c,
        ffrr_fixed_cost_income_statement_account_code_c,
        ffrr_fixed_income_statement_account_code_c,
        ffrr_forecast_header_primary_relationship_c,
        ffrr_forecast_transaction_line_relationship_c,
        ffrr_group_name_c,
        ffrr_include_active_value_c,
        ffrr_include_completed_value_c,
        ffrr_income_statement_account_c,
        ffrr_object_c,
        ffrr_parent_settings_c,
        ffrr_percentage_complete_c,
        ffrr_polisource_field_c,
        ffrr_primary_relationship_c,
        ffrr_rate_c,
        ffrr_recognized_to_date_value_c,
        ffrr_revenue_recognition_completed_c,
        ffrr_settings_level_c,
        ffrr_settings_type_c,
        ffrr_ssp_c,
        ffrr_start_date_c,
        ffrr_total_cost_c,
        ffrr_total_revenue_c,
        ffrr_total_units_c,
        ffrr_transaction_line_relationship_c,
        ffrr_use_in_revenue_contract_c,
        ffrr_value_type_c,
        ffrr_vsoepercent_c,
        ffrr_vsoerate_c,
        is_deleted,
        last_modified_by_id,
        last_modified_date,
        last_referenced_date,
        last_viewed_date,
        name,
        owner_id,
        system_modstamp,
        ffrr_group_c,
        ffrr_setting_uniqueness_c,
        ffrr_document_currency_rate_c,
        ffrr_dual_currency_c,
        ffrr_dual_currency_rate_c,
        ffrr_grouped_by_c,
        ffrr_home_currency_c,
        ffrr_analysis_item_1_c,
        ffrr_analysis_item_2_c,
        ffrr_analysis_item_3_c,
        ffrr_analysis_item_4_c,
        ffrr_company_c,
        ffrr_product_c,
        ffrr_salesforce_account_c,
        ffrr_fixed_true_up_account_code_c,
        ffrr_true_up_account_c,
        ffrr_deferred_revenue_to_date_c,
        ffrr_fixed_true_up_dual_account_code_c,
        ffrr_parent_relationship_paths_c,
        ffrr_revenue_schedule_source_lookup_c,
        ffrr_true_up_home_account_c,
        ffrr_revenue_schedule_line_lookups_c,
        ffrr_engagement_lookup_c,
        ffrr_recognized_to_date_value_dual_c,
        ffrr_deferred_revenue_to_date_home_currency_c,
        ffrr_include_in_true_up_c,
        ffrr_recognized_to_date_value_home_c,
        ffrr_true_up_dual_account_c,
        ffrr_deferred_revenue_to_date_dual_currency_c,
        ffrr_deferred_revenue_to_date_reporting_currency_c,
        ffrr_fixed_true_up_home_account_code_c

    from source

)

select * from renamed
