
with source as (

    select * from {{ source('raw_salesforce', 'pse_revenue_forecast_version_detail_c') }}

),

renamed as (

    select
        id,
        _fivetran_synced,
        created_by_id,
        created_date,
        currency_iso_code,
        is_deleted,
        last_modified_by_id,
        last_modified_date,
        name,
        pse_corp_currency_c,
        pse_corp_equal_split_milestone_p_c,
        pse_corp_equal_split_milestone_r_c,
        pse_corp_equal_split_milestone_s_c,
        pse_corp_equal_split_project_p_c,
        pse_corp_equal_split_project_r_c,
        pse_corp_equal_split_project_s_c,
        pse_corp_eva_s_c,
        pse_corp_expense_p_c,
        pse_corp_expense_r_c,
        pse_corp_milestone_p_c,
        pse_corp_milestone_r_c,
        pse_corp_milestone_s_c,
        pse_corp_misc_adjustment_p_c,
        pse_corp_misc_adjustment_r_c,
        pse_corp_opportunity_u_c,
        pse_corp_percent_complete_milestone_p_c,
        pse_corp_percent_complete_milestone_r_c,
        pse_corp_percent_complete_milestone_s_c,
        pse_corp_percent_complete_milestone_u_c,
        pse_corp_percent_complete_project_p_c,
        pse_corp_percent_complete_project_r_c,
        pse_corp_percent_complete_project_s_c,
        pse_corp_percent_complete_project_u_c,
        pse_corp_timecard_p_c,
        pse_corp_timecard_r_c,
        pse_equal_split_milestone_pending_c,
        pse_equal_split_milestone_recognized_c,
        pse_equal_split_milestone_scheduled_c,
        pse_equal_split_project_pending_c,
        pse_equal_split_project_recognized_c,
        pse_equal_split_project_scheduled_c,
        pse_eva_scheduled_c,
        pse_expense_pending_c,
        pse_expense_recognized_c,
        pse_milestone_c,
        pse_milestone_pending_c,
        pse_milestone_recognized_c,
        pse_milestone_scheduled_c,
        pse_misc_adjustment_pending_c,
        pse_misc_adjustment_recognized_c,
        pse_opportunity_c,
        pse_opportunity_unscheduled_c,
        pse_percent_complete_milestone_pending_c,
        pse_percent_complete_milestone_recognized_c,
        pse_percent_complete_milestone_scheduled_c,
        pse_percent_complete_milestone_unscheduled_c,
        pse_percent_complete_project_pending_c,
        pse_percent_complete_project_recognized_c,
        pse_percent_complete_project_scheduled_c,
        pse_percent_complete_project_unscheduled_c,
        pse_project_c,
        pse_revenue_forecast_version_c,
        pse_time_period_c,
        pse_time_period_end_c,
        pse_time_period_start_c,
        pse_timecard_pending_c,
        pse_timecard_recognized_c,
        system_modstamp,
        pse_opportunity_probability_c,
        pse_corp_opportunity_u_worst_c,
        pse_opportunity_unscheduled_best_c,
        pse_opportunity_unscheduled_worst_c,
        pse_corp_opportunity_u_best_c,
        pse_region_c,
        pse_practice_c,
        pse_group_c

    from source

)

select * from renamed
