
with source as (

    select * from {{ source('raw_github', 'github_events') }}

),

renamed as (

    select
        action,
        github_event,
        comment_author_type,
        comment_body,
        comment_created_at,
        comment_url,
        comment_id,
        comment_updated_at,
        comment_user_id,
        comment_user_name,
        issue_assignee_id,
        issue_assignee_name,
        issue_author_type,
        issue_body,
        issue_closed_at,
        issue_comment_count,
        issue_created_at,
        issue_url,
        issue_number,
        issue_state,
        issue_title,
        issue_updated_at,
        issue_user_name,
        issue_user_id,
        label_id,
        label_name,
        organization_id,
        organization_name,
        organization_url,
        pull_request_author_type,
        pull_request_base_ref,
        pull_request_base_repo_id,
        pull_request_base_repo_name,
        pull_request_base_repo_url,
        pull_request_base_repo_owner_id,
        pull_request_base_repo_owner_name,
        pull_request_base_sha,
        pull_request_body,
        pull_request_closed_at,
        pull_request_created_at,
        pull_request_head_ref,
        pull_request_head_repo_id,
        pull_request_head_repo_name,
        pull_request_head_repo_url,
        pull_request_head_repo_owner_id,
        pull_request_head_repo_owner_name,
        pull_request_head_sha,
        pull_request_head_user_id,
        pull_request_head_user_name,
        pull_request_url,
        pull_request_id,
        pull_request_issue_url,
        pull_request_merged,
        pull_request_merged_at,
        pull_request_number,
        pull_request_state,
        pull_request_title,
        pull_request_updated_at,
        pull_request_user_id,
        pull_request_user_name,
        pusher_email,
        pusher_name,
        repository_url,
        repository_id,
        repository_name,
        repository_owner_id,
        repository_owner_name,
        pull_request_review_author_type,
        pull_request_review_body,
        pull_request_review_commit_id,
        pull_request_review_url,
        pull_request_review_id,
        pull_request_review_state,
        pull_request_review_submitted_at,
        pull_request_review_user_id,
        pull_request_review_user_name,
        sender_url,
        sender_id,
        sender_name,
        timestamp,
        type

    from source

)

select * from renamed
