
with source as (

    select * from {{ source('raw_telemetry_ece', 'ece_history') }}

),

renamed as (

    select
        id,
        timestamp,
        remote_addr,
        agent,
        method,
        query_string_parameters,
        referrer,
        path,
        headers,
        headers_origin,
        headers_accept,
        headers_cloudfront_viewer_country,
        headers_cloudfront_forwarded_proto,
        headers_cloudfront_is_tablet_viewer,
        headers_cloudfront_is_mobile_viewer,
        headers_referer,
        headers_user_agent,
        headers_x_forwarded_proto,
        headers_cloudfront_is_smarttv_viewer,
        headers_host,
        headers_accept_encoding,
        headers_x_forwarded_port,
        headers_x_amzn_trace_id,
        headers_via,
        headers_x_amz_cf_id,
        headers_x_forwarded_for,
        headers_accept_language,
        headers_cloudfront_is_desktop_viewer,
        headers_content_type,
        geoip,
        geoip_continent_name,
        geoip_city_name,
        geoip_country_iso_code,
        geoip_region_name,
        geoip_location_lon,
        geoip_location_lat,
        body,
        body_clusters_stats_kibana_running_count,
        body_clusters_stats_elasticsearch_count,
        body_clusters_stats_elasticsearch_running_count,
        body_clusters_stats_count,
        body_clusters_stats_running_count,
        body_clusters_stats_kibana_count,
        body_license_uid,
        body_license_expiry_date_in_millis,
        body_license_start_date_in_millis,
        body_license_issued_to,
        body_license_max_instances,
        body_license_issue_date_in_millis,
        body_license_type,
        body_license_issuer,
        body_runners_stats_count,
        body_runners_stats_connected_count,
        body_allocators_stats_total_connected_capacity,
        body_allocators_stats_count,
        body_allocators_stats_used_capacity,
        body_allocators_stats_connected_count,
        body_allocators_stats_total_capacity,
        body_initialized,
        body_installation_id,
        body_ok,
        body_uuid,
        body_allocators_zones_stats,
        body_allocators,
        body_runners,
        body_clusters,
        user_agent,
        user_agent_patch,
        user_agent_major,
        user_agent_minor,
        user_agent_os,
        user_agent_os_minor,
        user_agent_os_major,
        user_agent_name,
        user_agent_os_name,
        user_agent_device,
        partition_date

    from source

)

select * from renamed
