name: "Ingest: Saas Hosted KPI Data"

on:
  # schedule:
  #   - cron: "0 9 * * *" # github actions run on UTC

  workflow_dispatch:

env:
  PYTHONVERBOSE: "x"
  ES_HOST: ${{ secrets.ES_HOST }}
  GOOGLE_APPLICATION_CREDENTIALS: ./keyfile.json
  KEYFILE: ${{ secrets.KEYFILE }}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_PAT }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ secrets.PY_VERSION }}
          cache: "pip"
      - name: Run Python Script
        run: |
          echo $KEYFILE > keyfile.json
          export GOOGLE_APPLICATION_CREDENTIALS="./keyfile.json"
          python -m pip install --upgrade pip
          pip install -r ./arch/loads/cloud_kpi/requirements.txt
          python ./arch/loads/cloud_kpi/deployments.py
